---  
title: "ms3R Batch Report"
author: Samuel D. N. Johnson
date: \today
geometry: letterpaper
nocaption: false
header-includes:
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage{array}
- \usepackage{multirow}
- \usepackage[table]{xcolor}
- \usepackage{wrapfig}
- \usepackage{float}
- \usepackage{colortbl}
- \usepackage{pdflscape}
- \usepackage{tabu}
- \usepackage{threeparttable}
- \usepackage{threeparttablex}
- \usepackage[normalem]{ulem}
- \usepackage{makecell}
- \usepackage{caption}
- \usepackage{pdflscape}
- \newcommand{\blandscape}{\begin{landscape}}
- \newcommand{\elandscape}{\end{landscape}}
always_allow_html: yes
params:
  batchDir: "~/Work/code/models/stockAssessment/multispecies/ms3R/Outputs/"
  groupFolder: "longGrid"
  prefix: "MPgrid"
output: 
  pdf_document:
    keep_tex: true
    fig_caption: true
    latex_engine: pdflatex
    template: ~/Work/write/templates/tex/TandF.latex
  html_document:
    self_contained: true
    toc: true
    toc_depth: 2
    toc_float: true
    df_print: kable
    keep_md: false
  word_document:
    df_print: kable
    reference_docx: /Users/sdnjohnson/Work/write/templates/docx/basic.docx
  bookdown::pdf_document2:
    keep_tex: true
    fig_caption: true
    latex_engine: pdflatex
    template: ~/Work/write/templates/tex/TandF.latex
    fig_width: 7
    fig_height: 6
  bookdown::html_document2:
    self_contained: true
    df_print: kable
    keep_md: false
    toc: true
    toc_depth: 2
    toc_float: true
    number_sections: false
  bookdown::word_document2:
    df_print: kable
    reference_docx: /Users/sdnjohnson/Work/write/templates/docx/basic.docx
---

# Batch Description

```{r, setup, message=FALSE, warning=FALSE, include=FALSE, echo = FALSE}

# I usually load my libraries up front to keep things organized
library( bookdown )
library( knitr )
library( kableExtra )
library( dplyr )
library( stringr )
library( tidyverse )
library( here )

knitr::opts_knit$set( fig.pos = 'p',
                      out.width = '100%', dpi=300, 
                      root.dir = params$batchDir,
                      message = FALSE, warning = FALSE, echo = FALSE )

options(warn = -1)

source(here("ms3Rplots.R"))
source(here("simSCAL.R"))
source(here("tools.R"))
source(here("stats.R"))
source(here("refPts.R"))

batchDir    <- params$batchDir
prefix      <- params$prefix
groupFolder <- params$groupFolder

# Count the number of fits in the batch directory
info.df <- readBatchInfo( params$batchDir) %>%
            filter( grepl(params$prefix, simLabel ) )


# Loop over the batch sims, and load their
# blobs, saving to a named list
nSims <- nrow(info.df)
batchBlobs <- vector(mode = "list", length = nSims )

for(simIdx in 1:nSims)
{
  # Recover Rdata file name
  localPath <- file.path(batchDir,info.df$simLabel[simIdx])
  simFolderFiles <- list.files( localPath )
  simFile <- simFolderFiles[grepl(".RData", simFolderFiles)]
  simPath <- file.path(localPath,paste(info.df$simLabel[simIdx],".RData",sep=""))

  # Load sim object
  load(simPath)
  # Assign to global environment
  assign( "blob",blob,pos=1 )

  # Save to batchBlobs
  batchBlobs[[simIdx]] <- blob
}

nS <- blob$om$nS
nP <- blob$om$nP
nT <- blob$om$nT
speciesNames <- blob$om$speciesNames
stockNames   <- blob$om$stockNames

# Make simulation performane stats
batchPerfStats <- lapply( X = batchBlobs, FUN = .simPerfStats, inclAgg=TRUE, exclNoTAC=TRUE )

statTable      <- do.call(rbind, batchPerfStats)  %>%
                  select(scenario, mp, stock, pBtGt.3B0, pBtGt.5B0, pUtGt.1HR:catchAAV, pBtGtHistSB:growthRate16yrs) %>%
                  arrange(scenario, -1*pBtGt.3B0,-1*pBtGt.5B0, -1*nYrsSOK, -1*avgLicSOK, -1*nYrsComm)

statTable$avgSOK_1000lbs <- statTable$avgSOK_t/0.453592

pmTable <- select(statTable, scenario, mp, stock, pBtGt.3B0, pBtGt.5B0, 
                  nYrsSOK:pondAAV, avgSOK_1000lbs, nYrsComm:catchAAV, pUtGt.1HR, 
                  avgUtGt0.1HR, pBtGtHistSB:growthRate16yrs)

# save csv of statTable
write.csv(pmTable, file.path(batchDir,'batchReports','pmTable.csv'), row.names=F)

# pm table for rw15_loPond

pm_rw15LoPondM <- subset(pmTable, scenario=='rw15_loPondM')
write.csv(pm_rw15LoPondM,  file.path(batchDir,'batchReports','pmTable_rw15LoPondM.csv'), row.names=F)

# Save Seperate tables for HS_30_100 and HS_50_60
hcr1 <- c('oSOK_HS50-60_HR0.1', 'cSOK_HS50-60_HR0.1','cSOK+SR_HS50-60_HR0.1', 
          'SR_HS50-60_HR0.1','NoFish')
hcr2 <- c('oSOK_HS30-100_HR0.1', 'cSOK_HS30-100_HR0.1','cSOK+SR_HS30-100_HR0.1', 
          'SR_HS30-100_HR0.1','NoFish')

pm_rw15LoPondM_hcr1 <- subset(pm_rw15LoPondM, mp %in% hcr1) %>% arrange(stock)
write.csv(pm_rw15LoPondM_hcr1 ,  file.path(batchDir,'batchReports','pmTable_rw15LoPondM_hcr1.csv'), row.names=F)

pm_rw15LoPondM_hcr2 <- subset(pm_rw15LoPondM, mp %in% hcr2) %>% arrange(stock)
write.csv(pm_rw15LoPondM_hcr2,  file.path(batchDir,'batchReports','pmTable_rw15LoPondM_hcr2.csv'), row.names=F)

message("All simulation objects loaded and ready to make batch report")

```

Batch report file for ms3R simulations.

Batch folder: `r params$batchDir`


```{r, batchTable, include = TRUE, echo = FALSE}
ScenMPtable <- info.df[,1:2]

kable(  ScenMPtable, escape = FALSE, 
        caption = "Scenarios and MPs in batch.", booktabs = T,
        align = rep("c",ncol(ScenMPtable))) %>%
  kable_styling(latex_options = c("striped", "scale_down","hold_position"),
                bootstrap_options = c("striped", "hover"))

```


```{r, captions, include = FALSE, echo = FALSE}
# Captions for different comparison tables

aggPerfTabCap <- "Aggregate level performance statistics."
jpsPerfTabCap <- "Juan Perez/Skincuttle (Sections 021/025) level performance statistics."
csPerfTabCap <- "Cumshewa/Selwyn (Sections 023/024) level performance statistics."
louPerfTabCap <- "Louscoone (Section 006) level performance statistics."

```


# Aggregate level performance

```{r, aggPerf, echo = FALSE}


aggStatTable <- subset(statTable, stock=='aggregate')


kable(  aggStatTable, escape = FALSE, 
        caption = aggPerfTabCap, booktabs = T,
        align = rep("c",ncol(aggStatTable))) %>%
  kable_styling(latex_options = c("striped", "scale_down","hold_position"),
                bootstrap_options = c("striped", "hover"))

```


# Individual stock performance

## Juan Perez/Skincuttle

```{r, jpsPerf, echo = FALSE, results = 'asis' }

jpsStatTable <- subset(statTable, stock=='JP/S')

kable(  jpsStatTable, escape = FALSE, 
        caption = jpsPerfTabCap, booktabs = T,
        align = rep("c",ncol(jpsStatTable))) %>%
  kable_styling(latex_options = c("striped", "scale_down","hold_position"),
                bootstrap_options = c("striped", "hover"))




```

## Cumshewa/Selwyn

```{r, csPerf, echo = FALSE, results = 'asis' }

csStatTable  <- subset(statTable, stock=='C/S')

kable(  csStatTable, escape = FALSE, 
      caption = csPerfTabCap, booktabs = T,
      align = rep("c",ncol(csStatTable))) %>%
  kable_styling(latex_options = c("striped", "scale_down","hold_position"),
              bootstrap_options = c("striped", "hover"))

```

## Louscoone

```{r, louPerf, echo = FALSE, results = 'asis' }

louStatTable  <- subset(statTable, stock=='Lou')

kable(  louStatTable, escape = FALSE, 
      caption = louPerfTabCap, booktabs = T,
      align = rep("c",ncol(louStatTable))) %>%
  kable_styling(latex_options = c("striped", "scale_down","hold_position"),
              bootstrap_options = c("striped", "hover"))

```


