---  
title: "ms3R Omniscient Manager Optimisation Report"
geometry: letterpaper
nocaption: false
header-includes:
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage{array}
- \usepackage{multirow}
- \usepackage[table]{xcolor}
- \usepackage{wrapfig}
- \usepackage{float}
- \usepackage{colortbl}
- \usepackage{pdflscape}
- \usepackage{tabu}
- \usepackage{threeparttable}
- \usepackage{threeparttablex}
- \usepackage[normalem]{ulem}
- \usepackage{makecell}
- \usepackage{caption}
- \usepackage{pdflscape}
- \newcommand{\blandscape}{\begin{landscape}}
- \newcommand{\elandscape}{\end{landscape}}
always_allow_html: yes
params:
  rootDir: "~/Work/code/models/stockAssessment/multispecies/ms3R/Outputs/sim_11122019143054/"
  RdataFile: "sim_11122019143054.RData"
output: 
  pdf_document:
    keep_tex: true
    fig_caption: true
    latex_engine: pdflatex
    template: ~/Work/write/templates/tex/TandF.latex
  html_document:
    self_contained: true
    toc: true
    toc_depth: 2
    toc_float: true
    df_print: kable
    keep_md: false
  word_document:
    df_print: kable
    reference_docx: /Users/sdnjohnson/Work/write/templates/docx/basic.docx
  bookdown::pdf_document2:
    keep_tex: true
    fig_caption: true
    latex_engine: pdflatex
    template: ~/Work/write/templates/tex/TandF.latex
    fig_width: 7
    fig_height: 6
  bookdown::html_document2:
    self_contained: true
    df_print: kable
    keep_md: false
    toc: true
    toc_depth: 2
    toc_float: true
    number_sections: false
  bookdown::word_document2:
    df_print: kable
    reference_docx: /Users/sdnjohnson/Work/write/templates/docx/basic.docx
---

## Omniscient Manager Optimisation

### Implied harvest control rules

```{r, figCaps, echo = FALSE, include = FALSE}
FvsBcap <- "Simulated fishing mortality vs spawning biomass from the omniscient manager simulations. 
Grey points show the individual points from every replicate and time step in the projection 
period, while thin dark grey lines show the smoothed relationship for every simulation 
replicate. Blue points show the biomass at the beginning of the projection period, while red
points show biomass at the end of the projection period."

CvsBcap <- "Simulated catch vs spawning biomass from the omniscient manager simulations. 
Grey points show the individual points from every replicate and time step in the projection 
period, while thin dark grey lines show the smoothed relationship for every simulation 
replicate. Blue points show the biomass at the beginning of the projection period, while red
points show biomass at the end of the projection period."
```

```{r, impliedHCRs, echo = FALSE, fig.cap = FvsBcap }
if( blob$ctlList$mp$omni$nKnots > 1)
  plotFvsB(blob)

```

```{r, impliedHCRs_catch, echo = FALSE, fig.cap = CvsBcap }
if( blob$ctlList$mp$omni$nKnots > 1)
  plotCvsB(blob)

```

### Objective function components

```{r, cplxTable, echo = FALSE}

  omniInfo <- .getOmniInfo( obj = blob )

  wtTable     <- omniInfo$wtTable
  cplxTable   <- omniInfo$cplxTable
  stockTable  <- omniInfo$stockTable


  kable(  cplxTable,
          escape = FALSE, 
          caption = "Objective function components and their weights for complex related quantities.", 
          booktabs = T,
          align = rep("c",ncol(statTable))) %>%
  kable_styling( latex_options = c("striped", "scale_down","hold_position"),
                 bootstrap_options = c("striped", "hover"))

```

```{r, stockTable, echo = FALSE}

  kable(  stockTable,
          escape = FALSE, 
          caption = "Objective function components and their weights for stock specific quantities.", 
          booktabs = T,
          align = rep("c",ncol(statTable))) %>%
  kable_styling( latex_options = c("striped", "scale_down","hold_position"),
                 bootstrap_options = c("striped", "hover"))

```

