# Introduction {#sec:introduction}

Welcome to report generation using `csasdown`. Included in this example document are many useful bits of information on how to write a reproducible report document using  the `csasdown` package, which is based on [Rmarkdown](https://rmarkdown.rstudio.com/) and [Bookdown](https://bookdown.org/). The information given in this example document should be used with all three `csasdown` document types: Research Document (`resdoc`), Science Response (`sr`), and Technical Report (`techreport`).

If you get stuck on anything, read the `csasdown` [README](https://github.com/pbs-assess/csasdown/blob/master/README.md) carefully and all the [Wiki pages](https://github.com/pbs-assess/csasdown/wiki). There are many tips and tricks located in those pages. 

Inserting a hyperlink in Rmarkdown is easy, just look at the code for the paragraph above. It is located in **01_introduction.Rmd**

Include references in the **bib/refs.bib** file in the same format as the example that is already in the file. This is called *BiBLaTeX* format. Once you have added the reference, you can cite it using Rmarkdown in the following ways:

1. In parentheses: `[@edwards2013]` - renders as: [@edwards2013]
2. Inline: `@edwards2013` - renders as: @edwards2013
3. Without author: `[-@edwards2013]` - renders as: [-@edwards2013]

Note that the year part of the citation is clickable and will take you directly to the reference in the References section.

Here is an example equation with the code used to generate it. Note that `csasdown` automatically numbers it on the right-hand side of the page. It does this consecutively throughout the document sections, but appendices are each numbered on their own, e.g. A.1, A.2, ... for Appendix A, and B.1, B.2, ... for Appendix B.

````
\begin{equation}
  1 + 1
  \label{eq:test}
\end{equation}
````

\begin{equation}
  1 + 1
  \label{eq:test}
\end{equation}

A reference can be included anywhere in the text, to refer to a section or appendix. For the first appendix in this document, the code looks like this: `\@ref(app:first-appendix)`. Adding that code inline will create a clickable link in the output file: See Appendix \@ref(app:first-appendix).

The code inside the parentheses comes from the tag after the header for the section. For the appendix, the whole header line looks like:

`# THE FIRST APPENDIX {#app:first-appendix}`

Everything in the curly braces except for the hash sign is the tag you use to reference a section.

This section's header line looks like this:

`# Introduction {#sec:introduction}`

And can be referenced like this: `\@ref(sec:introduction)` which renders to this: Section \@ref(sec:introduction).

A reference to the equation above looks like this: `\@ref(eq:test)` and renders to this: Figure \@ref(eq:test). The labels for any type of reference (except for bibliography citations) are shown in Table \@ref(tab:ref-tab).

```{r ref-tab}
refs_tab <- tribble(
     ~`Reference type`,                    ~`Rmarkdown code`,
             "Section",        "`\\@ref(sec:section-label)`",
          "Subsection",  "`\\@ref(subsec:subsection-label)`",
            "Appendix",       "`\\@ref(app:appendix-label)`",
            "Equation",        "`\\@ref(eq:equation-label)`",
              "Figure",         "`\\@ref(fig:figure-label)`",
               "Table",          "`\\@ref(tab:table-label)`")

csasdown::csas_table(refs_tab,
  align = c("r", "r"),
  caption = ifelse(french,
                   "French goes here",
                   "Reference types and their Rmarkdown reference codes."))
```
