# Results

## Stock assessment model fit

The stock assessment model was fit to the biomass indices and compositional
data outlined in the methods. Because the main application of the simulation
model was to generate realistic catches in the projections under each 
scenario/objective function, we focused the evaluation of model fit on 
biomass indices and commercial age data. 

Fits to all time series of biomass indices were almost unbiased, with 
mean residuals at most 0.07 standard deviations in absolute value. 
Despite low bias, there were significant trends in residuals for the modern 
commercial CPUE index for all QCS stocks, and WCVI Rock sole, as well as for 
the Hecate Strait assemblage survey for all three species (Figure S2); 
residual trends in the modern commerical and HS survey indices were not 
completely unexpected, as the modern trawl CPUE was a fishery dependent 
commercial catch-rate series with underlying targeting behaviour, while the 
fishery independent Hecate Strait Assemblage survey had a fixed station 
design with very large survey blocks. There were no trends in the residuals 
for the historical CPUE series, but this is due 
to the time-varying catchability applied to that series. Finally, the 
Synoptic survey residuals were unbiased and did not exhibit any 
significant trends. Because the closed loop simulations do not use any
simulated estimation model, these fits to

Fits to commercial trawl age compositions were also acceptable for
simulation purposes, showing that estimated trawl selectivity would 
produce realistic removals from each age class of the simulated DER 
complex. For Dover sole, the model matched the general shape of the 
time-averaged compositions well, with a slight under-estimation of female 
age compositions up until the modal age, and overestimation in the 
descending limb, before underestimating the plus-group age (Figure S3). 
Enligsh sole expected age compositions were similarly slightly too small 
up until the modal age, but the plus-group was over-estimated for both 
historic and modern trawl fleets (Figure S4). Finally, HSHG Rock sole had 
the best fit, with a small residual in the ascending limb for the 
historical fleet, and almost no residual error for the modern fleet 
(Figure S5). Residual patterns indicate that simulated fishing may
under-harvest older Dover sole and over-harvest older English sole
relative to the real DER complex, which lead to optimistic
conservation performance for Dover sole, and pessimistic for 
English sole, but we don't expect a large effect on the relative
results given that most simulated fishing will have harvest rates 
at or below $U_{MSY,MS}$. Fits to commercial length compositions were
of lower quality, but no simulated data was length based so we did not
present these or attempt to improve them.


Posterior chains sampled via Hamiltonian Monte-Carlo showed convergence 
for most model parameters, despite considerable uncertainty in many
posterior deviations. There were five model parameters with effective 
sample sizes below 400 and/or Rhat values above 1.01 (Figure S6). 
Three of those parameters were leading parameters (lntauObs_vec[11], 
thetaSelAlpha_sg[1], thetaSelBeta_sg[9]), while the remaining two 
parameters were recruitment process deviations (omegaR_vec[179,180]), 
which also crossed the more relaxed Rhat and ESS thresholds for deviation 
parameters [Question for Sean: try putting 
tighter priors on or fixing those pars, or just wait for the 
publication?]. Parameter coefficients of variation (standard error
relative to the mean) showed that there was considerable uncertainty in
most model hierarchical, process error, and time-varying catchability 
random walk deviation parameters, indicating that despite chain 
convergence for those parameters there is limited statistical power in the
data to inform their values, which is expected given that limited and 
low power data is what led to the use of a hierarchical stock
assessment model.

Biomass time series and single-species biological reference point estimates 
indicate that all DER complex stocks were in a healthy state in 2016 (Table 3). 
Three out of nine stocks exhibited 1-way trip dynamics (HSHG and QCS Dover, 
and QCS Rock, Figure 5), where biomass only depleted over the period 1956 - 
2016, while the remaining stocks showed signs of growth, usually after the mid 
1990s, which could indicate that the estimated trend was spurious and
more related to a switch in indices. Indeed, the two smaller English sole 
stocks (QCS and WCVI) exhibit large jumps in biomass in 1996/1997,
right as the historical trawl CPUE ends and modern trawl CPUE begins, jumping 
almost all the way back to unfished levels in QCS. While these dynamics may 
indicate spurious recruitment dynamics for these two stocks in the mid 
1990s, the absolute size of the stocks is a very small proportion of the 
overall complex and so is is considered a minor issue for this paper.

Commercial catchability scalars for the modern trawl fleet were estimated
as the mean log-residual between fishing mortality and trawl effort [eqref].
Estimates were similar among species in the HSHG (0.022 - 0.026) and 
QCS (0.014 - 0.016) areas, but more different in WCVI (0.012 - 0.025)
(Table 4). Estimates of fishing mortality were distributed evenly around
the mean catchability relationship for the 1996 - 2016 period, with the
exception of some outliers in WCVI at around 22 thousand hours of trawling
in 1996, where Rock sole's observed relationship was almost twice the 
mean, and Dover and English were about half as catchable (Figure S6). These 
outliers may show a non-linear relationship between effort and mortality, 
counter to our assumption but also a realistic case, either from improved 
targeting  behaviour (increasing relationship, e.g., Rock sole), or 
over-depletion (decreasing relationship, e.g., Dover and English soles), 
but these data are not powerful enough to draw any such conclusions. Given
the closure of the BC trawl fishery in 1995 due to overfishing concerns
and poor reporting, it is likely that the outliers show overdepletion 
and/or poor record keeping at the beginning of the at-sea observer program.

## DER complex time-varying inverse demand curves

Fitting the time varying inverse demand curve model (Appendix B) to
ex-vessel unit price data showed that all three DER complex species
had relatively elastic demand (i.e., $\lambda_s > 1$ for all species
$s$; Figure 7, demand curves). Over time, reference prices steadily 
dropped from around $1 per kg in 2006 to lows around $0.50/kg - $0.75/kg
in 2011/2012 (Figure 7, Price time series), before increasing for 2-3 
years, with English sole reaching its maximum recorded ex-vessel and 
reference price estimate in 2013. In 2014, all three species reference 
prices dropped again and converged around $0.50/kg, before increasing 
again to the some of the highest observed prices in 2015 (Dover), 
or 2016 (English, Rock). As expected from the reference point and
biomass estimates (Table 3) observed ex-vessel prices are, with the
exception of Dover sole in 2006, above the reference price, indicating
that catches are generally below the coast-wide maximum sustainable
yield for each species. Observed prices for English and Rock sole were
generally much higher then reference prices, which is again expected
given the price elasticity of demand is much higher for Dover sole,
leading to a flatter demand curve (Figure 7).

TODO: SCALE deltas by their standard deviation (post-fit estimate)

The blocks of decreasing and increasing reference prices are reflected
in the random walk deviations (Figure 7, RW deviations). Early in the 
period $\delta_{s,t} < 0$ for all three species, becoming positive 
for 2010-2013, and so on. While random walks were closed to unbiased 
with mean deviations of at most 0.08 in absolute value, random walk 
jumps became more variable over time, with devaitions larger than 
1.0 only occuring in the last three years of the period. While the
blocking and shift in variation could signal model misspecification 
(e.g., some latent unmodeled process), they could also be caused by 
the small sample size.



## Steady-state reference points

### Multi-species maximum yield

Multi-species effort/yield relationships, and the harvest rates that 
maximised multi-species complex yield, followed a similar pattern in 
HSHG and QCS, but differed in WCVI (Figure 8, compare Tables 3 and 4). 
In HSHG and QCS areas, the optimal effort $E_{MSY,p}$ produced lower 
optimal harvest rates for Dover sole and English sole (marginally) when 
compared to single species optimal harvest rates, while Rock sole
optimal harvest rates maximising multi-species yield were 20\% - 30\% 
higher than harvest rates maxmising Rock sole yield alone (compare
$U_{MSY}$, Tables 3 and 4). In the WCVI area, $E_{MSY}$ led to a 5\%
higher English sole harvest rate when maximising DER complex yield than
English sole yield alone, while Dover sole harvest rates differed by 
less than a percentage point between the single-species and multi-species
optima, and Rock sole was slightly lower. Despite some large differences 
in optimal harvest rates, differences in MSY_SS and MSY_MS were subtle 
for all stocks, with a decrease of at most 5\% from MSY_SS to MSY_MS
to a total catch of XX.

Resource rent at MSY was around $630,000 CAD across the three stock 
areas. The area with the highest resource rent was HSHG, attained at
the lowest effort of the three areas (Table 3). The QCS and WCVI
areas both had roughly equal equilibrium resource rents at MSY, with
QCS around 9% higher rent at 11% higher fishing effort.


### Multi-species maximum economic yield

Maximum economic yield (annual resource rent in 2016 dollars) for the 
DER complex trawl fishery was around $1.58m CAD (Table 4). Fishing effort 
achieving MEY was about one third of the effort level achieving MSY_MS for 
all areas. Similarly, the optimal harvest rates for MEY were around 40\% 
of the harvest rates for MSY_MS. Despite the large drop in effort and 
harvest rates, catch differences were small given the higher equilibrium 
biomass at the lower fishing effort. The total difference in DER complex 
equilibrium catch between $MSY_{MS}$ and $C_{MEY}$ was approximately 
1.2 kt, with individual stock catches differing by an average of 23\%, 
with a minimum difference of around 13\% for HSHG Rock sole. 

Similar to above, resource rent was highest in the HSHG area at the lowest 
effort, reflecting the higher biomass of all species in that area 
(Table 4). While optimal effort $E_{MEY}$ in QCS was about 25\% higher 
than in WCVI, the resource rent was about 40\% higher in the WCVI area. 
Higher WCVI rent is largely caused by the higher Dover sole biomass 
relative to English and Rock sole biomasses in the WCVI and the
higher commercial catchability of Dover sole in the WCVI, which compensated
for higher simulated fuel costs of fishing and increased rent in an
area which was effectively a single-species fishery.

As expected, producers received a small transfer of surplus from consumers
given the downward sloping demand curves with constant price elasticity 
of demand. At the estimated price elasticity of demand $\lambda_s$, maximum 
economic yield in each area was higher while optimal effort was lower 
(compare $MEY$ and $E_{MEY}$ columns in Tables 4 and S1), reflecting lower 
effort costs and higher revenues from artificial scarcity at lower quantity 
supplied. When $\lambda_s = \infty$, optimal effort was about 15\% higher
in HSHG and QCS areas, and about 7\% higher in WCVI.

At the assumed fuel costs, the resource rents of the DER complex fishery 
are dependent on technical interactions to remain positive. While it is 
profitable to fish each species individually at low effort levels, as 
effort increases at least one revenue curve drops below the marginal 
cost line before $E_{MEY}$ is reached (Figure 9). 

The optimal allocation of fishing effort among areas was independent of 
the total effort, and appeared largely determined by the distribution
of commercial catchability scalars within an area. For any fixed level 
of coast-wide effort $E$, the optimal allocation was always 
$\langle E_1, E_2, E_3 \rangle = \langle 0.25E, 0.42E, 0.33E \rangle$.
This allocation was very close to the ratio $\rho_p$ of inverse 
average commercial catchabilty scalars within an area to the sum
of inverse average catchabilities (Table 5 $1/\bar{q}^{(F)}$), defined by
\begin{align*}
\rho_p &= \frac{1/\bar{q}^{(F)}_p}{\sum_p 1/\bar{q}^{(F)}_p}, \\
\bar{q}^{(F)}_p & = \frac{1}{3} \sum_s q^{(F)}_{s,p}, \\
\end{align*}
indicating that the allocation is likely fixed based on $q^{F}_{s,p}$ 
values, and the price elasticity of demand $\lambda_s$ has a minor effect,
as the allocation was similar when $\lambda_s = \infty$ (Table S1).
The optimal allocation was also similar, but less so, to the relative 
allocation of effort $E_{MSY,MS,p}$ when maximising catch (Table 5).



## Dynamic reference points

Stochasticity had a small effect on dynamic approximations
to $U_{MSY}$. Median $U_{MSY}^*$ harvest rates were very close 
to steady-state $U_{MSY}$ harvest rates, differing by around half of a 
percentage point on average, or around 0.5\% of the steady state optimum 
(Table 6). In contrast, harvest rates under the NPV maximising objective 
functions produced $U_{MEY}^*$ rates that were consistently 
higher than the steady-state $U_{MEY}$ values by around 4 - 7 percentage
points, or 7\% - 40\% of steady state (compare harvest rates, Tables
4 and 6), which may be caused by asymmetry in the price random walk's
range in projections [**Waiting on reruns**]. Although dynamic $U_{MEY}^*$ median values were 
consistently higher than steady state equilibria, the distribution of 
dynamic harvest rates under NPV maximising objective functions contained 
the steady state solution (Figure 7). 

Median annual undiscounted resource rents under both objective functions 
were higher than the steady-state solution (compare resource rent columns, 
Tables 4 and 6), despite almost identical efforts and harvest rates under 
the catch maximising objective function. When 
maximising catch under the stochastic optimisation, median rent was over 
three times the steady state estimate in HSHG, around twice steady-state
in QCS, and 9\% lower in WCVI. The rent maximising objective function also 
produced higher resource rents than steady state solutions, extracting 
88\% higher rents in HSHG, 50\% higher in QCS, and 14\% higher in WCVI. 
Higher resource rents are caused by [check]
1. Higher biomass at start (development windfall)?
2. PED pushing rents up?
3. Asymmetry in the price range, so prices can climb higher. 
[**Waiting on reruns**]

I think it's #3. We can test with a short run with no PED and no
price devs.



## Targeting optimal harvest rates in practice


### Conservation performance

Targeting either MSY or MEY through static or dynamic harvest rates 
did not pose any conservation risk under either perfect or imperfect 
biomass information (Figure 8). For $U_{MSY}$ and $U_{MSY}^*$ harvest
rates, biomasses in the projection period were above the equilibrium 
values given in Tables 4 and 6, as catch needed to develop from current
levels to the higher optimal harvest rates, requiring a development
period to the long-term equilibrium (e.g. Figure 9). In contrast, 
$B_{MEY}^*$ and $B_{MEY}^*$ was not always lower than the current biomass 
for all DER complex stocks, leading to more varied trajectories in the 
projection as choke dynamics had a larger effect (e.g., Figure 10); 
however, $B_{MEY}$ and $B_{MEY}^*$ values were always higher than
$B_{MSY}$ values, meaning that conservation risk was always lower 
under $U_{MEY}^*$ and $U_{MSY}^*$, despite lower biomass values under
the higher $U_{MEY}^*$ and $U_{MSY}^*$ harvest rates. Differences 
were largest between $U_{MEY}^*$ and $U_{MEY}$, with the 
static $B_{MEY}$ between 10\% and 20\% higher than the $B_{MEY}^*$. 
Given the relative values of $B_{MSY}$, $B_{MEY}$, and $B_{MSY,SS}$,
biological risk was acceptable for all harvest rates, with the 5th 
percentile of biomass was always above 40\% of the single-species 
$B_{MSY,SS}$, the level under which a stock is often considered 
critically overfished in Canada [@DFO2006A-Harvest-Strat].



### Economic performance

Relative health of the DER complex stocks provided conditions under which
catch maximisation gave an economic windfall. Median NPV of under MSY 
harvest rates was between $3M and $6M higher than the NPV under MEY 
harvest rates (Table 8), depending on the information scenario, or an
average of $190,000 - $375,000 in annual undiscounted rent. While 
higher NPV under catch maximisation is counter to conventional 
wisdom and our steady-state and dynamic optima (Tables 4, 6), they were 
present in the DER complex simulations because of the relative health
of DER complex stocks at the start of the projection. In 2016, all stocks 
were well above their respective $B_{MSY,SS}$, providing a standing biomass 
to fish down in all areas, creating higher catches at lower efforts (i.e.,
higher CPUE). During development, resource rents under both catch and
NPV maximising harvest rates were almost identical, and began to diverge
around 2021 in the QCS and WCVI, and 2024 in HSHS (Figure 11). After 
divergence, annual rents from catch maximising harvest rates continued to 
grow for 2 - 3 years while annual rents under the NPV maximising harvest 
rates leveled off for the remainder of the projection period, which is the
development windfall. After the peak, median annual rents under $U_{MSY}$ 
and $U_{MSY}^*$ declined below the $U_{MEY}$ and $U_{MEY}^*$ median rent, 
and around the same time the lower 5th percentile started to drift into 
negative rents (i.e. a net loss due to fishing), indicating that on a longer
time horizon than 32 years, the NPV under $U_{MSY}$ target harvest rates 
would shrink below the NPV under $U_{MEY}$ target harvest rates.

Despite higher median NPV under MSY harvest rates, there was significantly
greater risk at the tails. Under either $U_{MEY}$ or $U_{MEY}^*$ harvest
rates, the $VAR-5\%$ was about \$5M higher than for MSY under perfect
info ($310,000 annual rent on average) and about \$3M ($190,000 annually) 
higher under simulated assessment errors (Table 8), reflecting lower 
absolute biomass under MSY targets and higher costs of 
effort required to maintain maximum catch once development has occured and 
biomass has settled around the new equilibrium. Furthermore, targeting 
higher $U_{MEY}^*$ harvest rates appeared to have asymmetric risk, 
providing benefits with very little risk of loss. Median NPV under 
$U_{MEY}^*$ harvest rates were around \$3M higher ($190,000 per year) 
than under steady state $U_{MEY}$ harvest rates for both information 
scenarios, while $VAR-5\%$ was around \$16M for both $U_{MEY}^*$ and
$U_{MEY}$ under both information scenarios, indicating very little 
difference in downside between harvest. In contrast, the $VAR-95\%$ was 
about \$6M higher for the $U_{MEY}^*$ harvest rate under both scenarios, 
indicating that the higher harvest rate from the stochastic optimisation 
takes advantage of more favourable price and recruitment stochasticity, 
giving a more favourable upside.


- Unclear whether this is a development effect or an artifact
    of using stochastic optimisation/omniscience/rational expectations
    to derive target HRs. How can we check? - wait for reruns with
    corrected price dist


Imperfect information appeared to insulate against economic loss
when setting TACs using $U_{MSY}$ and $U_{MSY}^*$. For both harvest
rates, median NPVs were between $400,000 and $640,000 higher when
TACs were set based on imperfect information, and the $VAR-5\%$ 
was around $2M higher ($125,000 per year). The difference
between information scenarios did not appear to affect the potential 
upside of maximising catch, with differences in the $VAR-95\%$ NPV 
between $140,000 and $210,000 over the projection period. 

Despite the insulating effect, imperfect information appeared to reduce 
rents under rent maximising harvest rates. Median NPVs and $VAR-95\%$ 
values were $1.7M - $2M ($100,000 - $125,000 per year) lower when TACs 
were set using imperfect information. Lower tails of NPVs under
$U_{MEY}$ and $U_{MEY}^*$ were less sensitive to the information 
level, with $VAR-5\%$ increasing by about $550,000 when setting 
TACs using perfect information under the steady state harvest rate, 
but decreasing by about $60,000 when using $U_{MEY}^*$. The opposite
effect of perfect information in $VAR-5\%$ values betwee $U_{MEY}$
and $U_{MEY}^*$ creates a downside of around \$590,000 to the more 
aggresive harvest rate, which translates to an average loss
of $40,000 annually, but does not represent realistic risk since 
perfect information is unachievable. 

As expected, there was very little difference between NPV distributions
when fishing using $U_{MSY}$ and $U_{MSY}^*$ (Table 8). Median and
$VAR-5\%$ NPVs were most different when setting TACs with perfect 
information, while $VAR-95\%$ was more different under the imperfect
information scenario. 














