# Discussion

In this paper, we developed a bio-economic modeling framework to derive 
fishery target reference points aimed at maximising total catch ($MSY_{MS}$) 
and economic yield ($MEY$) from a multi-species flatfish fishery. For
$MSY_{MS}$ reference points, optima were not significantly different betwen 
yield-per-recruit derivations or stochastic optimisation. In contrast, 
optimal harvest rates derived from $MEY$ reference points via YPR analysis 
were significantly higher than optimal harvest rates derived from the 
stochastic optimisation that integrated over an 80 year projection. Future
increases in household incomes drove down the unit price, indicating
possible diet switching from flatfish to more expensive cuts of meat
as median incomes increased [refs for meat offcuts].

Spatial heterogeneity and market demand were, as predicted, significant 
determinants of fishery reference points. Under YPR derivations, assuming 
that prices were constant (i.e., infinite PED) meant there was no transfer 
of surplus to consumers with higher catches via downward sloping demand
curves, resulting in higher optimal harvest rates and economic yields. 
In contrast, while the optimal allocation of effort was similar, the 
optimal harvest rates, yields, and rents were significantly 
different if demand was assumed to decrease with increasing price, 
indicating a transfer of surplus from consumers to producers is occuring
[@pascoe2018offsetting]. Under the stochastic optimisations of resource
rent, reductions in demand as household incomes increased had significant 
effects on the optimal allocation of fishing effort. Over time, total effort
was reduced, but the highest proportion shifted to the QCS area to target 
Rock sole in, which had no upper bound on its unit price thanks to
a lack of exogenous catch in the USA. These effects of temporal variability 
in market demand highlight a common argument against using MEY reference 
points: that the assumptions are only valid for a short time, which may 
have already passed, and therefore $MEY$ targets require constant 
updating to stay relevant [ref]. On the other hand, frequent model updates 
to check misspecification is a basic requirement of adaptive management 
[@walters1986adaptive], and updating economic assumptions/models with
more recent data at the same time is of low marginal cost.

The effect of ignoring technical interactions when setting TACs is highly
context dependent. For example, it's commonly assumed that any choke 
effects are inherently negative outcomes, as they limit harvesters' ability
to fully utilise a species' TAC, and that foregone yield represents
an economic loss to the fishery [@baudron2015adverse]. While this may be
true when a low-value species is limiting access to a high value speces,
we did not find it to be the case for the DER complex. Targeting 
single-species $MSY_{SS}$ reference points produced better economic and 
conservation outcomes than targeting multi-species $MSY_{MS}$ reference 
points for the DER complex. The superior performance when targeting 
single-species harvest rates was likely based on the similar unit price 
of all species, the healthy state of the DER complex in 2016, and the 
specific mix of catchabilities and demand curves. Those factors created a 
situation where choke effects generated by filling some species TACs and 
not others actually produced a net economic benefit. On average, choke 
species were fished to the target biomass of $B_{MSY,SS}$ implied by the 
harvest rate, while the remaining species started, and remained, well above
$B_{MSY,SS}$ as their TACs were underutilized. Simultaneously, rents 
increased as a result of higher CPUE for under-utilised species (differential rent), and increased unit prices 
via the lower catches (a transfer of surplus to the producer). A positive
effect of choke dynamics is consistent with our previous results that choke 
effects can protect against overfishing due to assessmnent errors 
[@johnson2021hierarchical]. It is sensible to expect that leaving some 
TACs underutilised would create negative outcomes; for example, when the 
choke species is rebuilding (e.g., Yelloweye Rockfish, *Sebastes 
ruberrimus*) and the under-utilised species is valued much higher (e.g., 
Pacific Halibut, *Hippoglossus stenolopis*) [grey lit?]. In contrast,
while the production may have been available in the DER complex for higher 
levels of fishing targeting $U_{MSY,MS}$, DER complex price elasticities 
of demand implied that the price would decrease, and benefits of the 
increased catch would accrue primarily to consumers, not producers. Moreover,
as time went by in simulations, reduction in price caused by increasing 
household incomes and the resulting decrease in demand further transferred
surplus from producers to consumers. 

Targeting MEY harvest rates may provide a proxy reference point that
approaches EBFM without the need to directly estimate ecosystem 
reference points. While the DER complex fishery operating model 
included technical interactions only, and including ecological interactions 
would certainly get closer to ecosystem reference points 
[@collie2001biological; @howell2021combining], there is limited data to 
parameterise those interactions for most systems, including the DER 
complex. Therefore, the assumptions required for modeling 
ecological processes may induce more uncertainty rather than less. Further, 
there is limted evidence of ecological interactions among DER complex 
species in other areas [@pikitch1987use; @wakefield1984feeding]. There 
is also limited tagging data observing movement of DER species among areas, 
and some potential biogeographical barriers that may limit movement. Even
if there were unobserved, significant ecological interactions, it may
be that technical interactions are enough to produce, in a rough sense, 
eco-system based fishery management objectives. For example, the lower
target harvest rates associated with $MEY$ objectives are inherently
more conservative, as they promote higher CPUE in order to reduce 
the costs of fishing and increase landed values through lower total 
landings. Higher CPUE is a function of higher biomass, leading to very low 
conservation risk. That higher standing biomass may implicitly meet ecosystem 
requirements, meaning that $MEY$ targets may represent a less data
intensive approximate approach to EBFM, thereby improving triple bottom
line management [@pauly2020msy; @benson2020performance]. However, this
is not always guaranteed, as when the landed value of species is
very different, it may be more profitable to extirpate the low
value species [@pascoe2015setting]. Future analyses could
include both ecological and technical interactions in an 
ecosystem or MICE operating model and simulation-test the benefits of 
incorporating one or both types of interactions into stock assessment and/or
TAC advice [@plaganyi2013integrating; @lucey2021evaluating].

The economic model we used was fairly simple, and produces upper bounds
on resource rents that may optimistically bias the net-present-values 
in the simulations. For example, fuel and crew share were the only 
variable costs included, but quota lease prices, which are a significant 
expense for many harvesters, were left out of the analysis. While crew 
share can be considered constant like we treated it here, the price of 
fuel is time-varying, meaning that the marginal cost of fishing in fact
changes year by year. However, time-varying fuel costs would require a 
model to project the price into the future, adding variability to the 
results [footnote for statscan] which would likely leave the main findings 
unchanged. Adding lease prices would add a layer of complexity where the 
allocation of effort would change over the course of a year, as when 
price/demand drops, the lease price also drops, except for choke 
species. Choke species quota becomes more valuable as TAC is decreased, 
as it is required for access to higher value species. Negative correlation 
between landed price and lease price would lead to interesting secondary 
market dynamics and may create arbitrage [@oostdijk2020catch]; however, 
including such dynamics would require more detailed effort dynamics, 
likely at the individual vessel level, which was not required for the 
research questions in this paper.

An earlier version of this work included experiments where stochastic optima
were estimated with and without correlation in price and recruitment. 
Optimal harvest rates were then used as targets in closed loop simulations,
cross tested against OM scenarios with and without the same correlation. 
While simulated correlation in recruitment and price deviations 
had an effect on the distribution of fishery outcomes (e.g., NPV, 
biomass), there was little effect on the estimated optimal harvest rates 
themselves, and even less effect on the relative risks associated with 
incorrectly assuming the presence or absence of harvest rates when setting 
TACs. This is consistent with recent research that found that synchrony
in recruitment process error among groundfish was dampened by their 
long-lived nature [@oken2020effects], with their standing stocks of 
biomass and longer delays until selected by the fishery almost 
completely compensating for synchrony. However, we do not assert that 
recruitment correlation among species and areas is not an important issue 
in spatial and multi-species fisheries management. Our case was likely 
limited by the lack of ecological interactions/movement among 
stocks/species. We predict that recruitment correlation would have 
more significance in multi-stock contexts that include spatial movement 
(e.g. shorter lived Atlantic Bluefin Tuna), where TACs in one area could 
affect the effective harvest rate induced by another area's TACs through 
stock mixing [@goethel2016incorporating]. Then, positive correlation in 
recruitments would likely strengthen feedback links between areas, creating 
more significant differences between target harvest rates derived under 
correlated and uncorrelated scenarios. Recruitment correlation would also 
play a larger role for short-lived species, such as invertebrates 
[@oken2020effects; @dichmont2006management3], or if it was explicitly 
considered in a model-based biomass estimation procedure, affecting
TACs through stock status estimates [@dichmont2006management3].

The modeling framework developed in this paper can be extended to 
to help answer ecosystem based fishery management questions with
global relevance. For example, the "30x30 initiative" aims to 
protect 30\% of global oceans in marine protected areas by 2030. However, 
there is considerable uncertainty about the effect that spatial planning 
has on the distribution of effort [@hopf2016fishery; @russo2014smart]. 
One approach would be to link effort allocation to the economic model 
to more closely simulate how harvesters choose where to expend fishing 
effort [@hilborn1987general; @marchal2013added; @tidd2012dynamic]. 
A simple, emergent version of this behaviour was observed in the 
stochastic optimisations of DER complex NPV. Another extension could 
evaluate predictors of choke effects, and how they relate to catch/quota 
balancing (TAC utilisation) observed in the past [@marchal2009catch; 
@branch2008matching]. TAC utilisations could be correlated with biomass 
indices and catch series to evaluate observable conditions that may lead 
to choke effects. Those predictors may then have practical utility as 
management 'meta-rules' that allow TACs to be scaled to permit sustainable 
overfishing of choke species to mitigate undesirable choke effects on 
high value species, within reason. Finally, an extension to multi-sector 
fisheries would be very valuable. Multiple gear types would create complex 
economic and catch yield surfaces, where the costs of fishing, catchability,
and selectivity are different for different sectors 
[@krigbaum2021increasing; @guillen2013estimating].  Economic demand may 
also be sector dependent, as different sectors sometimes sell in different 
markets based on the condition or size of landings (e.g., BC Sablefish 
long-line trap and hook fleets sell to Japan, while the trawl fleet sells 
their landings in continental North America). 




