\clearpage
# Tables



```{r tableCaps, echo = FALSE, include = FALSE, warning = FALSE}

procModelEqnsCap  <- "Hierarchical age/sex-structured stock assessment model
equations."

statModelEqnsCap  <- "AM statistical model equations for DER complex data 
likelihoods, and single- and multi-level prior distributions."

parEstTableCap <- "Estimates of biological population parameters, 
single-species reference points, and stock status in 2016 for all nine 
DER complex stocks."

ssRefPtsTabCap <- "Maximum likelihood estimates of maximum sustainable
multispecies yield ($MSY_{MS}$) and maximum economic yield ($MEY$) 
reference points for the British Columbia DER complex of flatfish. 
Effort (1000s of trawl hours) and rent (millons CAD\\$) are calculated 
by area, while catch ($MSY$, $C_{MEY}$, kt), biomass ($B_{MSY}$, 
$B_{MEY}$, kt), and harvest rate ($U_{MSY}$, $U_{MEY}$, unitless) 
are calculated by species within an area."

propEffTabCap <- "Proportions of inverse average catchability and 
the estimated optimal allocation of effort among areas."

dynEqHRTabCap <- "Optimal harvest rates $U_{MSY}$ and $U_{MEY}$, maximising 
multi-species catch and economic yield respectively, estimated from 
biological parameters under steady equilibrium assumptions, and dynamic 
approximations $U_{MSY}^*$ and $U_{MEY}^*$ estimated under all four 
correlation scenarios." 

dynEqNoCorrTabCap <- "Median values of dynamic approximations to 
maximum sustainable multispecies yield ($MSY_{MS}$) and maximum economic 
yield ($MEY$) reference points for the British Columbia DER complex of 
flatfish derived via stochastic optimisation. Effort (1000s of trawl hours) 
and annual resource rent (\\$M CAD) are calculated by area, while catch 
($MSY$, $C_{MEY}$, kt), biomass ($B_{MSY}$, $B_{MEY}$, kt), and harvest 
rate ($U_{MSY}$, $U_{MEY}$, \\%) are calculated by species within an area."

bioDistTabCap <- "Median and central 90\\% of biomass distributions 
for DER complex species in each area in 2048, taken over all simulation 
replicates for the simulated assessment errors and perfect information 
closed loop simulations."


discRentTabCap <- "Median and central 90\\% of the distribution of net 
present value of the DER complex fishery in the projection period, taken
over all simulation replicates for the simulated assessment errors and 
perfect information closed loop simulations. Net present value of resource 
rent is summed over all DER complex species and stock areas, and 
discounted by an annual rate of 5\\%."
```


```{r modelEqnTab, echo = FALSE, messages = FALSE, warnings = FALSE}

procModelEqns  <- read.csv("data/procModelEqns.csv", header = TRUE, stringsAsFactors = FALSE)

colnames(procModelEqns) <- c("No.", "Equation")

csasdown::csas_table( procModelEqns, escape = FALSE,
                      booktabs = TRUE, font_size = 10,
                      format = kable_format,
                      # linesep = "\\addlinespace",
                      caption = procModelEqnsCap,
                      align = c("c","l")) %>%
  kable_styling(latex_options = c("striped", "hold_position","scale_down"),
                bootstrap_options = c("striped", "hover")) %>%
  kableExtra::group_rows("Unfished Equilibrium States", 1, 5 ) %>%
  kableExtra::group_rows("Numbers-at-age", 6, 7 ) %>%
  kableExtra::group_rows("Biomass", 8, 11 ) %>%
  kableExtra::group_rows("Catch", 12, 16 ) %>%
  kableExtra::group_rows("Individual Growth", 17, 19 )
  


```

\clearpage

```{r hierSCALstatModelEqns, echo = FALSE, messages = FALSE, warnings = FALSE}

# statModelEqns  <- read.csv("data/statModelEqns.csv", header = TRUE, stringsAsFactors = FALSE)

statModelEqns <- tibble::tribble( 

  ~No.,        ~ModelEquation,
  # Observation model equations
  # Expected spawn indices
  "(O.1)",      "$\\displaystyle \\hat{I}_{s,p,f,t}   = q_{s,p,f,t} \\cdot B_{s,p,f,t} $",
  # Expected age comps
  "(O.2)",      "$\\displaystyle \\hat{u}_{a,x,s,p,f,t} = \\frac{ C_{a,x,s,p,f,t} } { \\sum_{a'} C_{a',x,s,p,f,t}}$",
  # Expected len comps
  "(O.2)",      "$\\displaystyle \\hat{u}'_{l,x,s,p,f,t} = \\frac{ \\mathcal{P}_{l,a,x,s,p} \\cdot s_{l,s,p,f} \\cdot N_{a,x,s,p,t} } { \\sum_{l'} \\mathcal{P}_{l',a,x,s,p} \\cdot s_{l',s,p,f} \\cdot N_{a,x,s,p,t}}$",

  # Now calculate biomass observation resids
  # "(L.1)",      "$\\displaystyle z_{p,t} = \\log \\frac{ I_{p,t} }{ \\hat{I}_{p,t} }$",
  # "(L.2)",      "$\\displaystyle q'_{p,t} = \\eta_{p,t} q_{p,4} + (1 - \\eta_{p,t}) q_{p,5}$",
  # "(L.3)",      "$\\displaystyle n_{p} = \\sum_{t = t_{0,p}}^T \\mathcal{I} (I_{p,t} > 0)$",
  # "(L.4)",      "$\\displaystyle Z_{p} = \\frac{1}{2\\tau^2_{p}} \\sum_{t = t_{0,p}}^T \\mathcal{I} (I_{p,t} > 0) z_{p,t}^2 $",
  # "(L.5)",      "$\\displaystyle d_p = \\sum_t \\left( \\mathcal{I}(I_{p,t} > 0) \\log( \\mathcal{P}_{p,t}) + \\mathcal{I}(I_{p,t} = 0) \\log( 1 - \\mathcal{P}_{p,t}) \\right)$",
  # "(L.6)",      "$\\displaystyle l_{1} = \\frac12 \\sum_{p = 1}^3 \\left( n_{p} \\cdot \\log \\tau_{p}^2 +  Z_{p} + d_p  \\right) $",

  # # Age composition likelihood
  # "(A.1)",      "$\\displaystyle \\mathfrak{C}_g = \\left[ \\rho_g^{j - i} \\right]_{i,j}$",
  # "(A.2)",      "$\\displaystyle \\mathfrak{K} = \\left[ I_{A-1} \\vert 1 \\right]$",
  # "(A.3)",      "$\\displaystyle V_g = \\mathfrak{K} \\cdot C_g \\cdot \\mathfrak{K}^T$",
  # "(A.4)",      "$\\displaystyle W_{p,g,t} = \\frac{ \\mbox{mean} ( {n^{Age}_{p,g,t}} ) }{ n^{Age}_{p,g,t} }$",
  # "(A.5)",      "$\\displaystyle \\mathfrak{B}_{p,g,t} = \\sum_{a = 1}^A \\mathcal{I}( u_{a,p,g,t} > 0.02)$",
  # "(A.6)",      "$\\displaystyle \\vec {\\iota}_{p,g,t} = \\langle log(u_{a,p,g,t} / u_{\\mathfrak{B}_{p,g,t},p,g,t}) - log(\\hat{u}_{a,p,g,t}/\\hat{u}_{\\mathfrak{B}_{p,g,t},p,g,t} \\rangle_a$",
  # "(A.7)",      "$\\displaystyle \\hat{\\tau}^{age}_{p,g} = \\left( \\frac{ \\sum_{t} \\frac{1}{W_{p,g,t}^2}(\\vec{\\iota}_{p,g,t})^T \\cdot V_g^{-1} \\cdot \\vec{\\iota}_{p,g,t}}{\\sum_{t} \\mathfrak{B}_{p,g,t} } \\right)^{0.5}$",
  # "(A.8)",      "$\\displaystyle l_{2} = \\sum_{p,g} \\left( \\sum_{a,t} \\log u_{a,p,g,t} + \\log \\hat{\\tau}^{age}_{p,g} \\sum_{t} (\\mathfrak{B}_{p,g,t} - 1) + \\frac12 \\sum_t \\log \\vert V_g \\vert + \\sum_{t} (\\mathfrak{B}_{p,g,t} - 1)\\log W_{p,g,t} \\right)$",

  # # Process error priors
  # "(P.1)",      "$\\displaystyle p_{1} = \\sum_{p,t} \\omega_{p,t}^2$",
  # "(P.2)",      "$\\displaystyle p_{2} = \\sum_{a,p} \\left(\\omega^{init}_{a,p}\\right)^2$",
  # "(P.3)",      "$\\displaystyle p_{3} = \\sum_{p,t} \\epsilon_{p,t}^2$",
  
  # # Shrinkage priors
  # "(P.4)",      "$\\displaystyle p_{4} = \\left( \\sum_{p} \\epsilon_{M,p}^2 \\right) + \\frac{1}{2 s_M^2} (\\log M_0 - \\log m_M )^2$",
  # "(P.5)",      "$\\displaystyle p_{5} = \\sum_g \\left( \\left( \\sum_{p} \\epsilon_{s,50,p,g}^2 + \\epsilon_{s,Step,p,g}^2 \\right) + \\frac{1}{2 (s_g^{s^{50}})^2} (\\log s^{50}_g - \\log( m_g^{ s^{50} }) )^2 + \\frac{1}{2 (s_g^{s^{Step}})^2} (\\log s^{Step}_g - \\log( m_g^{ s^{Step} }) )^2 \\right) $",

  # # Other priors
  # "(P.6)",      "$\\displaystyle Catchability priors$",
  # "(P.6)",      "$\\displaystyle Obs Err SD $",
  # "(P.7)",      "$\\displaystyle Corr Coeff $",
  # "(P.8)",      "$\\displaystyle logisticRegressionPars $",

  # Objective function
  "(F.1)",      "$f = l_1 + l_2  + p_1 + p_2 + p_3 + p_4 + p_5 + p_6 + p_7 + p_8$",
)

colnames(statModelEqns) <- c("No.", "Equation")

csasdown::csas_table( statModelEqns, escape = FALSE,
                      booktabs = TRUE, font_size = 10,
                      format = kable_format,
                      linesep = "\\addlinespace",
                      caption = statModelEqnsCap,
                      align = c("c","l")) %>%
  kable_styling(latex_options = c("striped", "hold_position","scale_down"),
                bootstrap_options = c("striped", "hover"))  %>%
  kableExtra::group_rows("Observation models", 1, 3 ) 
  # kableExtra::group_rows("Spawn index data likelihood", 3, 8 ) %>%
  # kableExtra::group_rows("Age composition data likelihood", 9, 16 ) %>%
  # kableExtra::group_rows("Process error prior density functions", 17, 19 ) %>%
  # kableExtra::group_rows("Hierarchical shrinkage prior density functions", 20, 21 ) %>%
  # kableExtra::group_rows("Priors on other parameters", 22, 24 ) %>%
  # kableExtra::group_rows("Objective function (negative posterior density)", 25, 25 )





```

\clearpage

```{r modelFitTable, echo = FALSE, warning = FALSE}

parEstTable <- makeParEstTable(simObj) %>%
                arrange(  match( Stock, c("HSHG","QCS","WCVI")),
                          match( Species, c("Dover","English","Rock")))

parEstTable <- parEstTable[,-2]


colnames(parEstTable) <- c( "Species",
                            "$B_0$",
                            "$R_0$",
                            "$M_m$",
                            "$M_f$",
                            "$h$",
                            "$B_{MSY}$",
                            "$U_{MSY}$",
                            "$MSY$",
                            "$B_{2016}$",
                            "$B_{2016}/B_0$",
                            "$B_{2016}/B_{MSY}$" )

csasdown::csas_table( parEstTable, escape = FALSE,
                      booktabs = TRUE, font_size = 10,
                      format = kable_format,
                      # linesep = "\\addlinespace",
                      caption = parEstTableCap,
                      align = c("l",rep("c",ncol(parEstTable)-1))) %>%
  kable_styling(latex_options = c("hold_position","scale_down"),
                bootstrap_options = c("striped", "hover"))  %>%
  kableExtra::group_rows("HSHG", 1, 3 ) %>%
  kableExtra::group_rows("QCS", 4, 6 ) %>%
  kableExtra::group_rows("WCVI", 7, 9 ) 

```

\clearpage

\blandscape

```{r ssRefPtsTable, echo = FALSE, warning = FALSE}

statRefPts <- makeStatMSEqbriaTab(blob)
ssRefPtsTab <- statRefPts

colnames(ssRefPtsTab) <- c( "Stock",
                            "Species",
                            "$q^F$",
                            "$E_{MSY}$",
                            "$\\pi \\left( \\sum MSY_{MS} \\right)$",
                            "$MSY_{MS}$",
                            "$B_{MSY,MS}$",
                            "$U_{MSY,MS}$",
                            "$E_{MEY}$",
                            "$MEY$",
                            "$C_{MEY}$",
                            "$B_{MEY}$",
                            "$U_{MEY}$")

csasdown::csas_table( ssRefPtsTab, escape = FALSE,
                      booktabs = TRUE, font_size = 10,
                      format = kable_format,
                      # linesep = "\\addlinespace",
                      caption = ssRefPtsTabCap,
                      align = c( "l", "l", rep("c",ncol(ssRefPtsTab)-2))) %>%
  kable_styling(latex_options = c("striped", "hold_position","scale_down"),
                bootstrap_options = c("striped", "hover"))  %>%
  add_header_above( header = c( " " = 3,
                                "DER complex maximum yield" = 5,
                                "Maximum Economic Yield" = 5),
                    bold = TRUE)

```

\elandscape

\clearpage

```{r propEffTable, echo = FALSE, warning = FALSE}

# We're gonna bodge this up from a couple sources.
qComm  <- statRefPts$qComm
qCommHSHG <- mean(qComm[2:4])
qCommQCS  <- mean(qComm[6:8])
qCommWCVI <- mean(qComm[10:12])

meanqComm <- c(1/qCommHSHG,1/qCommQCS,1/qCommWCVI)
meanqComm <- meanqComm/sum(meanqComm)

propEmey_p <- statRefPts$Emey[c(1,5,9)]
propEmey_p <- propEmey_p/sum(propEmey_p)
propEmsy_p <- statRefPts$Emsy[c(1,5,9)]
propEmsy_p <- propEmsy_p/sum(propEmsy_p)


# Get non-eqbm table too
noCorrEqbriaTab <- makeDynEqbriaTab(  "./data/dynEqbriaTables",
                                      scenario = "noCorr")

propDynEmey_p <- noCorrEqbriaTab$Emey[c(1,5,9)]
propDynEmey_p <- propDynEmey_p/sum(propDynEmey_p)
propDynEmsy_p <- noCorrEqbriaTab$Emsy[c(1,5,9)]
propDynEmsy_p <- propDynEmsy_p/sum(propDynEmsy_p)


propEffTable <- matrix( nrow = 3, ncol = 6)
colnames(propEffTable) <- c(  "Area",
                              "$1/\\bar{q}^{(F)}$",
                              "$E_{MSY,MS}$",
                              "$E_{MEY}$",
                              "$E^*_{MSY,MS}$",
                              "$E^*_{MEY}$" )
propEffTable <- as.data.frame(propEffTable)
propEffTable[,"Area"] <- c("HSHG","QCS","WCVI")
propEffTable[,2] <- round(meanqComm,3)
propEffTable[,3] <- round(propEmsy_p,3)
propEffTable[,4] <- round(propEmey_p,3)
propEffTable[,5] <- round(propDynEmsy_p,3)
propEffTable[,6] <- round(propDynEmey_p,3)

csasdown::csas_table(  propEffTable, escape = FALSE,
                      booktabs = TRUE,
                      font_size = 10,
                      format = kable_format,
                      caption = propEffTabCap,
                      align = c("l","l",rep("c",ncol(propEffTable)-2)) ) %>%
      kable_styling(latex_options = c("striped", "hold_position","scale_down"),
                bootstrap_options = c("striped", "hover")) %>%
      add_header_above( header = c( " " = 2,
                                "Steady State" = 2,
                                "Dynamic (noCorr)" = 2),
                    bold = TRUE)


```



\blandscape
<!-- 
\clearpage

{r dynEqHRtable, echo = FALSE, warning = FALSE}
dynEqHRTab <- makeSpeciesDynEqTable( file = "./data/dynEqbriaTables/dynEqHR.csv" )

dynEqHRTab <- dynEqHRTab[,-1]
colnames(dynEqHRTab) <- c("Scenario", rep(c("Dover","English","Rock"),3))
rownames(dynEqHRTab) <- NULL



csasdown::csas_table( dynEqHRTab, escape = FALSE,
                      booktabs = TRUE,
                      font_size = 10,
                      format = kable_format,
                      caption = dynEqHRTabCap,
                      align = c("l",rep("c",ncol(dynEqHRTab)-1)) ) %>%
      kable_styling(latex_options = c("striped", "hold_position","scale_down"),
                bootstrap_options = c("striped", "hover")) %>%
      add_header_above( header = c( " " = 1,
                                    "HSHG" = 3,
                                    "QCS" = 3,
                                    "WCVI" = 3),
                    bold = TRUE) %>%
      kableExtra::group_rows("Maximising Catch", 1, 5 ) %>%
      kableExtra::group_rows("Maximsing NPV", 6, 10 )



 -->



\clearpage

```{r dynEqTabNoCorr, echo = FALSE, warning = FALSE}

csasdown::csas_table( noCorrEqbriaTab, escape = FALSE,
                      booktabs = TRUE,
                      font_size = 10,
                      format = kable_format,
                      caption = dynEqNoCorrTabCap,
                      align = c("l","l",rep("c",ncol(noCorrEqbriaTab)-2)) ) %>%
      kable_styling(latex_options = c("striped", "hold_position","scale_down"),
                bootstrap_options = c("striped", "hover")) %>%
      add_header_above( header = c( " " = 2,
                                "DER complex maximum yield" = 5,
                                "Maximum Economic Yield" = 5),
                    bold = TRUE)


```

\elandscape


\clearpage

```{r closedLoopDiscRentTables, echo = FALSE, warning = FALSE}
perfInfoTab <- read.csv("./data/perfInfoPerfTables/dynEqDiscRentDist.csv",
                        row.names = 1, stringsAsFactors = FALSE)[,-c(1,3:7)]

simErrTab   <- read.csv("./data/simAssErrPerfTables/dynEqDiscRentDist.csv",
                          row.names = 1, stringsAsFactors = FALSE)[,-c(1,3:7)]

scenNames <- c("noCorr")
mpNames <- c("MSY","noCorr.MSY","MEY","noCorr.MEY")

mpScenGrid <- expand.grid(corrScen = scenNames, MP = mpNames)
mpScenGrid$scenMPname <- paste(mpScenGrid$corrScen,mpScenGrid$MP,sep = ".")


# Need to transpose, make stocks into colnames,
# turn row-names into scenario and HR columns
perfInfoTab <- t(perfInfoTab)
colnames(perfInfoTab) <- perfInfoTab[1,]
perfInfoTab <- perfInfoTab[-1,]
perfInfoTab <- as.data.frame(perfInfoTab)
scenMPnames <- rownames(perfInfoTab)
perfInfoTab$scenMPname <- scenMPnames

simErrTab <- t(simErrTab)
colnames(simErrTab) <- simErrTab[1,]
simErrTab <- simErrTab[-1,]
simErrTab <- as.data.frame(simErrTab)
scenMPnames <- rownames(simErrTab)
simErrTab$scenMPname <- scenMPnames

perfInfoTab <- perfInfoTab %>% 
                left_join( mpScenGrid, by = "scenMPname") %>%
                dplyr::select( MP,
                              cwPerfInfo = BC ) %>%
                arrange(  match(MP,mpNames) )

discRentTab <- simErrTab %>% 
                left_join( mpScenGrid, by = "scenMPname") %>%
                dplyr::select(  MP,
                                cwSimErr = BC ) %>%
                arrange(  match(MP,mpNames) ) %>%
                left_join( perfInfoTab, by = c("MP"))

colnames(discRentTab) <- c( "Target HR",
                            "Simulated Errors",
                            "Perfect Info")

discRentTab[,1] <- c( "$U_{MSY}$",
                     "$U^*_{MSY}$",
                     "$U_{MEY}$",
                     "$U^*_{MEY}$" )


csasdown::csas_table( discRentTab, escape = FALSE,
                      booktabs = TRUE,
                      font_size = 10,
                      format = kable_format,
                      caption = discRentTabCap,
                      align = c("l",rep("r",ncol(discRentTab)-1)) ) %>%
      kable_styling(  latex_options = c("striped", "hold_position","scale_down"),
                      bootstrap_options = c("striped", "hover")) %>%
      add_header_above( header = c( " " = 1,
                                    "DER Complex NPV ($M)" = 2),
                        bold = TRUE)







```

