---  
title: "A bio-economic modelling approach to estimating risks from multi-species and single-species harvest strategies for a spatially heterogeneous, technically interacting, flatfish fishery."
author: 
  - Samuel D. N. Johnson (corresponding)
  - Sean P. Cox
  - Duncan Knowler
affil:
  - School of Resource and Environmental Management,
    Simon Fraser University,
    8888 University Drive,
    BC, Canada
email:
  - samuelj@sfu.ca
  - spcox@sfu.ca
  - djk@sfu.ca
abstract: |
  There is little known about the relative conservation and economic 
  risks of applying single- and multi-species harvest strategies to 
  mixed groundfish fisheries. To explore those risks, a bio-economic 
  modeling framework is defined for the multi-species, 
  spatially heterogeneous right-eyed flounder (*Plueronectidae Spp.*) 
  complex in British Columbia, Canada. Harvest strategies based on
  single- and multi-species maximum sustainable yield ($MSY$) and maximum 
  economic yield ($MEY$) reference points are defined, where multi-species
  reference points incorporate technical interactions among species. The 
  conservation and economic risks are estimated via stochastic, 
  closed-loop simulation, in which each strategy is used to set catch
  limits for three management areas defined for the BC flatfish fishery. 
  Conservation risks are measured as the probability of overfishing each 
  individual population, while economic risks are measured by comparing the 
  5th percentiles of net present values under each strategy, for each area 
  and for the entire BC coast. We show that strategies based on $MEY$ 
  produce better conservation and economic performance than strategies
  based on either single-or multi-species $MSY$ reference points.

date: \today
bibliography: /Users/sdnjohnson/Work/Library/library.bib
natbib: true
biblio-style: plainnat
csl: /Users/sdnjohnson/Work/write/templates/csl/cjfas.csl 
geometry: letterpaper
toc: false
fontsize: 12pt
lineno: true
csl-refs: true
params:
  fit: "fit_base_MCMC"
  sim: "sim_baseRun_invDem"
  baseDir: "docs/refPtsDER/data"
  redoPlots: TRUE
numbersections: true
appendix: false
output: 
  pdf_document:
    citation_package: natbib
    keep_tex: true
    fig_caption: true
    latex_engine: pdflatex
    template: ~/Work/write/templates/tex/basic.latex
  bookdown::pdf_document2:
    citation_package: natbib
    keep_tex: true
    fig_caption: true
    latex_engine: pdflatex
    template: ~/Work/write/templates/tex/basic.latex
  html_document:
    self_contained: true
    df_print: kable
    keep_md: true
  bookdown::html_document2:
    self_contained: true
    df_print: kable
    keep_md: true
  word_document:
    df_print: kable
    reference_docx: /Users/sdnjohnson/Work/write/templates/docx/basic.docx
  bookdown::word_document2:
    df_print: kable
    reference_docx: /Users/sdnjohnson/Work/write/templates/docx/basic.docx
---

```{r setup, echo=FALSE, cache=FALSE, message=FALSE, results='hide', warning=FALSE}
library(knitr)
if (is_latex_output()) {
  knitr_figs_dir <- "knitr-figs-pdf"
  knitr_cache_dir <- "knitr-cache-pdf"
  fig_out_type <- "pdf"
  kableFormat <- "latex"
} else {
  knitr_figs_dir <- "knitr-figs-docx"
  knitr_cache_dir <- "knitr-cache-docx"
  fig_out_type <- "png"
  kableFormat <- "pandoc"
  options(knitr.table.format = "pandoc")
}
fig_asp <- 0.618
fig_width <- 6
fig_out_width <- "6in"
fig_dpi <- 180
fig_align <- "center"
fig_pos <- "htb"
opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = "#>",
  fig.path = knitr_figs_dir,
  cache.path = knitr_cache_dir,
  fig.asp = fig_asp,
  fig.width = fig_width,
  out.width = fig_out_width,
  echo = FALSE,
  #  autodep = TRUE,
  #  cache = TRUE,
  cache.comments = FALSE,
  dev = fig_out_type,
  dpi = fig_dpi,
  fig.align = fig_align,
  fig.pos = fig_pos
)
options(tinytex.verbose = TRUE)
options(xtable.comment = FALSE)
options(kableExtra.latex.load_packages = TRUE)
options(knitr.kable.NA = '')


source(here::here("docs/refPtsDER/SCALscripts","SCALfuns.R"))
source(here::here("docs/refPtsDER/SCALscripts","plots.R"))
source(here::here("docs/refPtsDER/SCALscripts","SCALrefPts.R"))
source(here::here("mseRtools.R"))
source(here::here("tools.R"))
source(here::here("ms3Rplots.R"))



```

```{r load-libraries, cache=FALSE}
# add other packages here:
library(kableExtra)
library(wesanderson)
library(tidyverse)
library(coda)
library(MASS)
library(tmbstan)
library(chemometrics)
library(mvtnorm)
library(RColorBrewer)
library(csasdown)
```

```{r loadStuff, echo = FALSE, include = FALSE, warning = FALSE}
reports <- .loadFit(params$fit, baseDir = params$baseDir )

repObj <- c(reports$repOpt, reports$data)
repObj <- calcRefPts(repObj)
repObj <- renameReportArrays(repObj = repObj, datObj = reports$data )

fYear   <- reports$fYear
nS      <- repObj$nS
nP      <- repObj$nP
nT      <- repObj$nT
nF      <- repObj$nF
species <- reports$ctlList$data$species
stock   <- reports$ctlList$data$stock
fleets  <- reports$gearLabs

priceModel <- readRDS("./data/priceModelIV.rds")

source(here::here("stats.R"))
source(here::here("ms3Rplots.R"))
source(here::here("ms3RrefPts.R"))

# Also want to load a base version of
# the OM for all its info... can we just pull the
# repObj from there????
.loadSim(sim = params$sim, baseDir = params$baseDir )
simObj <- blob


# Load priceModel
load("./data/DERcplxPriceFlexModel.RData")
```



