# Introduction


Multi-species fisheries management attempts to balance
the harvest levels of complex combinations of interacting
target and non-target species that vary in abundance and
productivity. Different species productivities imply different 
responses to exploitation, and therefore different optimal 
harvest rates. For an individual species, the optimal harvest 
rate (e.g. the harvest rate associated with maximum sustainable 
yield) is often derived from life-history characteristics via an 
age-structured stock assessment (or similar approach), ignoring 
potential multi-species interactions that may 
affect individual demographic rates that determine optimal 
harvest rates [@gislason1999single; @collie2001biological], 
or make it impossible to simultaneously achieve the 
optimal harvest rate for all species [@pikitch1987use]. 
Optimal harvest rates are of limited utility on their own, 
even if known *a priori*, as setting catch limits based on target 
harvest rates requires an estimate of species abundance, which may
be the output of a fisheries stock assessment model fit 
to data in the presence of uncertainty [@hilborn1992quantitative]. 
Taken together, the above makes multi-species fishery 
management a complex task under the best of conditions.

Technical interactions exist between species that co-occur 
in non-selective fishing gear, and are a defining 
characteristic of multi-species fisheries 
[@pikitch1987use; @punt2002evaluation]. Despite the 
central role of technical interactions in determining
how multi-species fisheries management actions affect 
species outcomes, technical interations are often ignored 
when setting catch limits or determining target exploitation 
rates [@ono2017management; @kempf2016msy], and the single-species 
paradigm prevails in most developed multi-species fisheries, 
with harvest decisions made on a single-species basis, given the 
output of a single-species stock assessment model. 
Catch-limits set for individual species without 
considering technical interactions will often lead to 
sub-optimal fishery outcomes [@ono2017management; 
@punt2011calculating; @punt2020multispecies]. For example, 
under-utilisation of catch-limits could occur when technically 
interacting quota species are caught at different rates (i.e., 
catchability) by a common gear, or have different productivity 
levels, leading to a choke constraint in which one species 
quota is filled before the others [@baudron2015adverse]. 
Choke constraints are generally considered negative outcomes 
for multi-species fishery performance, as they reduce harvester 
profitability as quota for choke species becomes rare
[@mortensen2018identifying], limiting access to fishing 
grounds and potentially becoming more valuable 
than the landed value of the choke species.

In practice, setting catch limits to meet target harvest rates 
for individual species in any fishery requires an estimate of 
speciess abundance. Estimating species abundance in the presence of
uncertainty is the central challenge of fisheries stock assessment
[@hilborn1992quantitative], and that challenge is compounded when 
species data are insufficient for stock assessment models to extend 
reliable estimates of abundance. Where data limitations exist, data 
pooling is sometimes used to extend stock assessments to complexes 
of similar, interacting groups of fish [@appeldoorn1996model], 
such as spatially pooling the same species across multiple 
spatial strata, pooling multiple species of the same taxonomic 
group within an area, or more simply lumping all data-limited 
species in an area. In any pooled stock assessment, models 
estimate a complex-mean productivity, and catch limits that
are based on them will tend to overfish some species and 
underfish others, potentially leading to collapse [@gaichas2012assembly]. 
Hierarchical multi-species stock assessment models are a compromise 
between problematic data-pooling and single-species approaches, 
allowing for data sharing between multiple species within 
a complex through hierarchical shrinkage prior distributions on 
model parameters that represent biological similarities or 
technical interactions [@thorson2015giants]. Shared priors
shrink species specific parameters towards an estimated complex mean 
value, improving model convergence for data poor species and basing 
estimates on available data rather than strong assumptions like 
fixed parameters or strongly informative priors [@jiao2009hierarchical; 
@jiao2011poor; @punt2011among].

Although hierarchical stock assessments produce better
estimates of species biomass and productivity than single-species
methods when fit to poor-quality data [@johnson2018evaluating], 
it is unclear whether this improved statistical performance 
translates into better management outcomes. On the one hand,
improving assessment model statistical performance may 
sacrifice improved fishery outcomes, as large assessment errors 
caused by poor quality data may improve management system knowledge 
by increasing contrast in the data through successive rebuilding 
events (i.e. adaptive learning) [@walters1986adaptive]. 
On the other hand, biomass may collapse or harvesters
may divest from the fishery due to over- or under-exploitation 
because the adaptive learning failed to occur sufficiently 
quickly. Improving the rate of adaptive learning may be 
possible via hierarchical modeling of spatially replicated 
groundfish stocks, because the shared priors may import 
adaptive learning behaviour between areas and use them 
to improve stock assessments in other areas 
[@collie1991adaptive].

In this paper, we investigated whether hierarchical 
stock assessment models improved management performance
in a simulated multi-species, data-limited fishery. The 
simulated fishery was modeled on a complex of Dover sole, 
English sole, and southern rock sole - three species of 
right-eyed flounders (*Pleuronectidae spp.*) fished off the 
coast of British Columbia, Canada, in three management areas. 
Closed-loop feedback simulation was used to estimate fishery
outcomes when catch limits were set based on estimates 
of biomass from five alternative state-space surplus 
production models under three data scenarios. Assessment 
models were either fit to species specific data as single-species
or hierarchical multi-species models, or fit to data pooled 
spatially across management units, pooled across species 
within a spatial management unit, or totally aggregated across 
both species and spatial management units. Management 
performance of each assessment model was measured 
as cumulative absolute loss in catch and stock biomass, 
measured against the simulated catch and biomass trajectories 
generated by simulating the harvest decisions of an omniscient 
manager, who can see future recruitments and adjust annual 
effort to maximise total complex yield [@walters1998evaluation; 
@walters2004fisheries]. 

<!-- Most research on stock assessment
and harvest performance in multi-stock and multi-species 
fisheries focuses on mismatches between the spatial 
scales of harvest decision and the true underlying stock
dynamics [@benson2015evaluating; @punt2018estimates], or on the 
comparative performance when considering technical interactions 
between target and non-target (bycatch) species when setting 
catch limits based on independent single-species stock 
assessments [@ono2017management]. Further, research on 
hierarchical stock assessment procedures has been focused 
on assessment bias under different levels of model 
complexity [@punt2011among; @jiao2016integrating;
@jiao2011poor; @jiao2009hierarchical; @johnson2018evaluating]. -->

<!--   Data-pooled catch
limits were allocated among species and stocks relative 
to their most recent fishery-independent survey biomass 
index. Data scenarios successively reduced the total length 
of the available biomass indices, removing data series 
until only recent fishery indepent indices were used. 
 -->

<!-- 
  From old abstract:
    Single-species assessment methods, at best, 
    only implicitly include multi-species interactions through natural mortality and 
    recruitment process errors, which are not suitable for capturing technical interactions 
    between multiple species and fishing gear. Ignorance of technical interactions when 
    setting TACs will often lead to sub-optimal fishery outcomes, such as under-utilised TACs from choke
    effects in output-controlled fisheries. In turn, these sub-optimal outcomes may
    degrade the information linkage between stock-status and management decisions
    by lowering the statistical power of catch data, reducing the efficacy
    of stock assessment models. These issues are further compounded in situations where 
    data or management resources are limited, exemplified by short time-series of 
    fishery independent observations or limited biologica data, or the 
    structure of the management decision is mismatched to the spatial structure of the system, 
    exemplified by aggregating multiple spatial stocks or species into one management unit. In
    those situations, assessments will usually estimate an average productivity for the 
    complex, leading to underfishing for some members, and overfishing for others.
    In this paper, we simulate a spatially structured, multi-species flatfish fishery, and
    test the performance of multiple management procedures that are based on assessment methods 
    often used to deal with data limitations in multi-species fisheries, including 
    data-pooling across spatial strata or across multiple species. Procedure performance
    is measured as absolute loss in catch and biomass compared to the outcome 
    of omniscient manager simulations where the objective was to maximise
    complex yield. To include technical interactions in our management system,
    we defined harvest control rules that used the optimal equilibrum fishing effort 
    derived from the omniscient manager simulations. We found that the performance
    of a management procedure relative to omniscient management was largely
    dependent on whether the most catchable (or choke) species in each 
    area had TACs set to an optimal level. If the choke species has the 
    'optimal' TAC, and the other species in the complex had TACs that 
    would overfish, then the entire complex would be managed closer to 
    the levels of the omniscient manager. If the choke species TAC was 
    set too high, then the outcomes would be to generally overfish the
    complex, and similarly, if the choke species TAC was set too low
    then TACs would be left underfished for the complex.
 -->



<!-- Single-species management often ignores the fact that fishing is inherently non-selective,
and therefore in most cases, fishing effort results in the
simultaneous catch of multiple species, which are said to 
have technical interactions [@punt2002evaluation]. Management decisions, 
such as setting total allowable catches (TACs), are often made for
a given species based on the output of species specific
stock assessments, if they even exist. Those single-species 
assessments, at best, are only able to implicity include 
multi-species ecological interactions in the form of 
natural mortality rates and recruitment process errors 
[@albertsen2017connecting], but are completely unable 
to explicitly capture technical interactions.  -->

<!-- Ignorance of technical interactions among species 
while setting TACs in multi-species fisheries will often 
lead to sub-optimal fishery outcomes [@ono2017management;
@punt2002evaluation]. For example, under-utilisation of TAC 
could occur when multiple technically interacting quota species 
are caught with very different gear availability (catchability), 
leading to one species quota being filled faster than the others 
and creating a choke point in the management system 
[@baudron2015adverse]. In turn, the under-utilised TACs may 
create uninformative catch data, which can degrade stock assessment 
performance over successive fishing seasons, and may 
create a reinforcing feedback loop that will lead to 
reduced data quality in the long term. If unarrested, 
data quality reducing feedback loops could weaken the 
information linkage required to take management 
actions commensurate with stock status. -->

<!-- Difficulties linking management decisions to stock 
status are compounded when data or management resources 
are limited [@Carruthers2014Evaluating].
Data limitations or low commercial value often preclude 
extending the best management practices (e.g., 
Management Strategy Evaluation) to all species in a multi-species
fishery. Data pooling is often used to extend stock assessments to 
complexes of multiple stocks of similar, interacting species
of fish, where similar may be defined in a biological
sense, or in a sense more related to overlapping management unit 
boundaries [@gaichas2012assembly]. More recently, hierarchical stock 
assessment models are being applied to extend assessments 
in multi-species and multi-stock complexes where better data exists 
for some subgroup of the complex, and there are biological reasons 
to expect biological parameters to be similar among species in
the complex [@thorson2015giants]. For example, 
estimates of management parameters and stock status are improved in 
scenarios where data is of low statistical power (i.e., short 
time series or noisy observations) when hierarchical multi-stock 
surplus production models penalise survey catchability and intrinsic
growth rate by shrinkage priors, compared to single-stock
models fit to the same data [@johnson2018evaluating]. -->




<!-- In this paper, we simulated a spatially structured, 
multi-species flatfish fishery, and tested the performance 
of multiple management procedures that were based on assessment 
methods that are often used to deal with data limitations in 
multi-species fisheries. We conditioned our simulated fishery 
on the complex of Dover, English, and Rock soles in British Columbia, 
Canada [*Pleuronectidae spp*]. These three species 
co-occur along the BC coast, are caught 
together in directed trawl fisheries, and are surveyed by 
the same multi-species trawl survey. While time series
of catch and commercial CPUE exist for all species and 
areas since the 1950s, all fishery independent observation 
series are quite noisy and some are very short, making this 
complex a good candidate for the application of data-limited 
stock assessment methods. We tested both single-stock and 
hierarchical multi-stock surplus production assessment models 
[@johnson2018evaluating], with skewed yield curves to match 
simulated age-structured populations based on on the 
JABBA-Select model [@winker2018jabba; @winker2020jabba]. 
We also tested data aggregation methods, including across spatial 
strata (coastwide models), across multiple species within a 
stratum (data-pooled), or total aggregation. Management procedure 
performance was measured as absolute or relative loss in catch and 
biomass compared to the outcome of simulations where an 
omniscient manager is maximising total system yield 
[@walters1998evaluation]. To include technical interactions 
in our simulated fishery system, we derived a commercial
catchability ratio between fishing effort and mortality
for each species/stock combination, and allowed future
fishing effort to increase until at least one TAC was fully
utilised, representing a fully integrated output 
control fishery with technical interactions, as in 
British Columbia's trawl fishery. Total allowable catches 
were set as constant removal rates based on either multi-species 
optimal harvest rates, derived from adding single-species 
yield curves with respect to effort [@mueter2006using; 
@punt2020multispecies], or traditional single-species 
optimal harvest rates derived from the operating model 
yield curves.  -->





