# Methods


## British Columbia's flatfish fishery

The multi-species complex of right-eyed flounders in British Columbia
(BC) is a technically interacting group of flatfishes managed over the
BC coast (Figure 1). Although there are several right-eyed flounders in 
BC waters, we focus on the three species, indexed by $s$, Dover 
sole ($s = 1$), English sole ($s = 2$), and southern Rock sole 
($s = 3$), which we hereafter refer to as Rock sole. Taken together, 
these species comprise a multi-stock complex (DER complex), managed as 
part of the BC multi-species groundfish fishery.

The DER complex is managed in three spatially distinct stock areas, 
indexed by $p$ (Figure 1) [@PRIFMP2015]. From north to south, the 
first stock area - Hecate Strait/Haida Gwaii (HSHG, $p = 1$) - extends from 
Dixon Entrance and north of Haida Gwaii, south through Hecate Strait. 
The second stock area - Queen Charlotte Sound (QCS, $p = 2$) - extends 
from the southern tip of Haida Gwaii to the northern tip of Vancouver 
Island. Finally, the third area - West Coast of Vancouver Island (WCVI, 
$p = 3$) - extends from the northern tip of Vancouver Island south to 
Juan de Fuca Strait. These areas are aggregates of PFMA major statistical
areas, and are primarily delineated by management breaks, although
there are oceanographic features that may separate each of the stocks
as defined here (e.g., gullies in the QCS area, and strong currents at 
the northern tip of Vancouver Island).

Each species/area combination had commercial trawl catch for the entire 
history (1956 - 2016), two commercial catch rate series, and at least one 
survey biomass index time series for each species (Figure 2), for a total of
four distinct fleets, indexed by $f$. The two commercial fishery 
catch-per-unit-effort (CPUE) series span 1976 - 2016, split between a 
Historical trawl fishery (1976 - 1995, $f = 1$) and a Modern trawl fishery 
(1996 - 2016, $f = 2$), with the split corresponding to pre- and 
post-implementation of an at-sea-observer programme, respectively. The fishery 
independent trawl survey biomass indices were the biennial Hecate Strait 
Assemblage survey in the HSHG area (1984 - 2002, $f = 3$), and the 
Multi-species Synoptic Trawl Survey, which operated every year but 
alternates between areas, so it is effectively a biennial survey in all 
three areas (2003 - 2016, $f = 4$).


## Closed-loop feedback simulation framework

Closed-loop simulation is often used to evaluate proposed
feedback management systems. In fisheries, closed-loop simulation evaluates 
fishery management system components, such as stock assessment models or 
harvest decision rules, by simulating repeated applications of these
components, while propagating realistic errors in monitoring data, 
stock assessment model outputs, and harvest advice 
[@de-la-Mare1998Tidier-fisherie; @cox2008practical; @cox2013roles]. At the 
end of the simulation, pre-defined performance metrics are used to
determine the relative performance of the system components being tested. 

Our closed-loop simulation framework included a stochastic operating
model, representing stock and fishery dynamics and generating observations
with uncertainty, and an assessment model component that estimated stock 
biomass from simulated observations and fishery catches. The
operating model simulated population dynamics of a spatially 
stratified, multi-species flatfish complex in response to a 
multi-species trawl fishery in each of the three stock areas. 
Although total fishing effort was not restricted across the 
entire area, effort in each individual area was allocated 
such that no species-/area-specific catch exceeded the 
species-/area-specific total allowable catch (TAC). Within an area, 
fishing effort was allowed to increase until at least one 
species-/area-specific TAC was fully caught.

The simulation projected population dynamics for each species in each
area (total nine stocks) forward in time for $32$ years, or two Dover sole 
generations [longest generation time; @seber1997estimation], with annual 
simulated assessments, harvest decisions, and catch removed from the 
population from 2017 - 2048. The following four steps summarise the 
closed-loop simulation procedure for each projection year $t$:

1. Update stochastic population dynamics and
generate new realized catch $C_{s,p,t}(E_{p,t})$ in each
area from effort (eq \ref{eq:FqE});
2. Generate new observation data $I_{s,p,f,t}$ 
(eqs \ref{eq:startIdx}-\ref{eq:endIdx})
3. Apply an assessment model (defined below) to estimate the
spawning biomass for the upcoming year $\widehat{B}_{s,p,t+1}$ and
an optimal harvest rate $\widehat{U}_{MSY,s,p}$ (eq \ref{eq:amBio});
4. Scale the estimated optimal harvest rate to an estimated multi-species 
optimal harvest rate, and use it with the biomass forecast to generate a 
total allowable catch $TAC_{s,p,t+1}$, allocated among species/areas if 
using a pooled method (eqs \ref{eq:startHR} - \ref{eq:endHR});
5. Allocate effort $E_{p,t+1}$ to fully realise at least
one TAC from step 4 in each stock area (eq \ref{eq:maxE}).


### Operating Model

The operating model (OM) was a multi-species, multi-stock age- 
and sex-structured population dynamics model (Appendix A). 
Population life-history parameters for the operating
model were estimated by fitting a hierarchical age- and 
sex-structured model to data from the real DER complex.

Fishing mortality for individual stocks was scaled to
commercial trawl effort via species-specific catchability
parameters, i.e., 
\begin{equation}
F_{s,p,t} = q^{F}_{s,p} \cdot E_{p,t},\label{eq:FqE}
\end{equation}
where $F_{s,p,t}$ is the fishing mortality rate applied to species $s$ 
in stock-area $p$ by fleet $f$ in year $t$, and $q^{F}_{s,p}$ is the 
commercial catchability coefficient scaling trawl effort $E_{p,t}$ in area $p$ 
to fishing mortality (Table 1). The relationship in equation 
\ref{eq:FqE} implies a multi-species maximum yield $MSY_{MS,p}$ within 
each area, from which we derived the corresponding effort $E_{MSY,MS,p}$,
species yield $MSY_{MS,s,p}$, the biomass $B_{MSY,SS,s,p}$ at which 
multi-species maximum yield is achieved, and the optimal harvest rate 
$U_{MSY,MS,s,p} = MSY_{MS,s,p}/B_{MSY,MS,s,p}$ that produced multi-species 
maximum yield, which are all given in Table 1 [@pikitch1987use]. The 
single-species optima, which are also in Table 1, are derived in the usual 
way by maximising single-species yield $MSY_{SS,s,p}$, produced at the 
optimal biomass $B_{MSY,SS,s,p}$ by applying the optimal harvest rate
$U_{MSY,SS,s,p} =  MSY_{SS,s,p}/B_{MSY,SS,s,p}$.


<!-- The above effort model implies a multi-species maximum yield for 
the trawl fishery in each area, depending on individual species 
productivity, commercial trawl catchability, and relative 
catchabilities among species in the area [@pikitch1987use; 
@punt2011calculating], i.e.,
\begin{equation*}
MSY_{MS,p} = \max_{E} Y_{MS} 
    \left( E, q^{F}_{1,p}, q^{F}_{2,p}, q^{F}_{3,p}, Q_p \right),
\end{equation*}
where $E$ is the total commercial trawl fishing effort, $q_{s,p}$ 
is the commerical trawl catchability coefficient scaling fishing 
effort to fishing mortality for species $s$ 
in area $p$, and $Q_p$ is the set of life-history parameters for 
all DER complex species in area $p$. The function $Y_{MS}$ is the 
total multi-species yield in area $p$ as a function of fishing 
effort $E_p$ (Figure 2, heavy black lines), defined as the sum of 
species-specific equilibrium yields
\begin{equation*}
Y_{MS,p} \left(E_p, q^{F}_{1,p}, q^{F}_{2,p}, q^{F}_{3,p}, Q_p \right)
 = \sum^3_{s=1} Y_{SS,s,p} (E_p, q_{s,p}, Q_{s,p} ),
\end{equation*}
where $Q_{s,p}$ is the subset of $Q_p$ containing life history 
parameters for species $s$ in area $p$, and the function $Y_{SS,s,p}$ 
is the traditional single-species yield curve expressed as a 
function of effort rather than fishing mortality (Figure 2, 
coloured lines).

The level of fishing effort producing multi-species maximum 
yield $MSY_{MS,p}$ in area $p$ is defined as 
\begin{equation*}
E_{MSY,p} = {\argmax}_{E} Y_{MS} 
    \left( E, q^{F}_{1,p}, q^{F}_{2,p}, q^{F}_{3,p}, Q_p \right),
\end{equation*}
with arguments defined above (Figure 2, vertical dashed line). 
The fishing effort level $E_{MSY,p}$ has an associated equilibrium 
biomass $B_{MSY,MS,s,p}$ and yield 
\begin{equation*}
MSY_{MS,s,p} = Y_{SS,s,p} (E_{MSY,p}, q^{F}_{s,p}, Q_{s,p} )
\end{equation*}
for each species $s$ (Figure 2, three lower horizontal dashed 
lines showing individual species yield), which differ from the 
single-species $B_{MSY}$ and $MSY$ when commercial catchability 
scalars differ between species. -->

For simulated fishing in the projection time period, the fully realised
TAC depended on the choke effects determined by relative catchabilities 
and absolute biomass levels of each species within an area. To simulate the
choke effects, we allocated the maximum fishing effort to each area
required to fully utilize the TAC of at least one species, but 
never exceed the TAC of any one of the three species, i.e.,
\begin{equation}\label{eq:maxE}
E_{p,t+1} = \max \{ E ~|~ C_{s,p,t+1}(E) \leq TAC_{s,p,t+1} \forall s \},
\end{equation}
where $C_{s,p,t+1}(E)$ is the catch of species $s$ when effort $E$ 
is applied in area $p$ in year $t+1$ (the method for determining 
TACs is explained below). We used maximum effort instead of an 
explicit effort dynamics model because the former captured choke 
effects present in the real fishery system, while reflecting the
output controlled BC groundfish fishery, for which there is no explicit
limit on the total amount of fishing effort expended by license holders.


### Surplus production stock assessment models

At each time step $t$, simulated annual assessments were used to 
estimate the expected future spawning biomass estimate $\widehat{B}_{t+1}$ 
via a state-space Schaefer production model [@schaefer1954some; 
@punt2003extending], modified to better approximate the 
biomass-yield relationship underlying the age-/sex-structured 
operating model [@pella1969generalized; @winker2018jabba].
We extended the @johnson2018evaluating hierarchical state-space 
model to fit a multi-species, spatially stratified complex,
as well as fit a single-stock model to data from individual 
or data-pooled stocks, via the biomass equation
\begin{equation}\label{eq:amBio}
B_{s,p,t+1} = \left[ B_{s,p,t} + U_{MSY,s,p} \cdot \frac{m_{s,p}}{m_{s,p}-1} 
                  \cdot B_{s,p,t} \cdot \left(1 - \frac{1}{m_{s,p}} \cdot \left( \frac{B_{s,p,t}}{B_{MSY,s,p}} \right)^{m_{s,p} - 1}\right) - C_{s,p,t}\right] e^{\zeta_{s,p,t}},
\end{equation}
where the management parameters $MSY_{s,p}$ (optimal single-species 
yield) and $U_{MSY,s,p}$ (optimal single-species harvest rate) are 
the leading model parameters, $B_{MSY,s,p} = MSY_{s,p} / U_{MSY,s,p}$ 
is the biomass at which $MSY_{s,p}$ is acheived under the optimal 
harvest rate, $m_{s,p}$ is the Pella-Tomlinson parameter controlling 
skew in the biomass/yield relationship (derived from operating model 
yield curves), and $\zeta_{s,p,t}$ are annual process error deviations. 

In total, we defined the following five potential assessment 
model configurations (Figure 3):

1. Total Pooling (1 management unit);
2. Species Pooling (3 management units, independent parameters);
3. Spatial Pooling (3 species, independent parameters);
4. Single-species (9 management units, independent parameters);
5. Hierarchical Multi-species (9 management units, hierarchical priors);

\noindent where the number of management units is shown in parentheses 
(i.e., delete subscripts in eq. 7 for species or stock-area as 
appropriate, e.g., Spatial Pooling models have no $p$ subscript). 

Prior distributions on optimal yield $MSY_{s,p}$, optimal harvest rate
$U_{MSY,s,p}$, catchability $q_{s,p,f}$, and process error deviations
$\zeta_{s,p,t}$ were defined for each assessment model, with unbiased 
prior means based on the true operating model values (Online 
supplmental, Table S.1). While unbiased prior distributions are not 
possible to define in practice, our research question focused 
on the effect of the five AM structures on management performance when 
setting TACs based on AM estimates of biomass and productivity. While 
priors certainly affect those estimates, there is considerable variation 
in how an analyst might choose prior mean values for biological 
parameters, and those choices become more uncertain as data are reduced. 
For example, an analyst might choose a prior mean of average catch over 
an agreed historical period as the $MSY$ prior mean, and choose either 
a conservatively low value based on a review of stock assessments for 
similar species, or if it is available, the ratio of catch to an index 
of biomass in the same historical period to inform a prior mean
$U_{MSY}$ value. In cases where time-series of data are short, there 
may be no appropriate period for formulating such priors, while
noisy data (e.g., commercial CPUE) lack sufficient statistical 
power to draw parameter estimates away from biased mean values, 
especially when priors may be informative in the presence of data 
limitations. We based our unbiased priors on the OM to keep priors 
as similar as possible among AMs, thereby avoiding variation in 
performance caused by different prior choices.


### Data generation for assessment models

Time series of catch, commercial CPUE, and relative biomass indices were 
simulated in the historical and projection periods for fitting assessment 
models. While it is more usual to use the actual historical data in most 
closed loop simulations, we decided that given that pooled data must be 
simulated, simulating all data series removed any effect of the difference 
between simulated and real data
on performance between pooled and non-pooled AMs. The Historical fishery CPUE 
and Hecate Strait Assemblage survey were simulated only for the periods shown 
in Figure 2, but the Modern fishery CPUE and Synoptic trawl survey biomass 
index were also simulated in the projection period. All biomass indices were
simulated with log-normally distributed observation error deviations with 
precision based on the conditioning assessment (Table A.1, Appendix A).

Biomass indices for individual stocks were all simulated as relative
biomass with observation error
\begin{equation}\label{eq:startIdx}
\bar{I}_{s,p,f,t} = q_{s,p,f} \cdot B_{s,p,f,t},
\end{equation}
where $\bar{I}_{s,p,f,t}$ is the index without observation error,
$q_{s,p,f}$ is the catchability coefficient for species $s$ 
and stock-area $p$, and $B_{s,p,f,t}$ is the biomass of 
species $s$ in stock-area $p$ vulnerable to fleet $f$ in 
year $t$. For the Assemblage and Synoptic fishery independent
surveys ($f = 3,4$), the catchability coefficients $q_{s,p,f}$ were 
trawl efficiency estimates from the conditioning assessment. For 
commercial CPUE, catchability coefficients were estimated by the
conditioning assessment by assuming that catch rates were an unbiased 
relative index. While the assumption that catch rates were an unbiased
relative index likely increased the information contained in the 
simulated CPUE indices over the real data, the large CVs estimated
by the conditioning assessment retain realistic variation despite
removing any systematic bias from the simulated indices.

The method for generating pooled catch and biomass index data depended on 
the data type. Catch data were pooled by summation, and the index data were 
pooled according to the stock-specific definition above. For Assemblage 
and Synoptic survey biomass indices, pooled indices without 
observation error were defined as
\begin{align} 
\bar{I}^{pooled}_{s,f,t}  & = \sum_{p} \mathbb{1}(I_{s,p,f,t} > 0) \cdot q_{s,p,f} \cdot B_{s,p,f,t} \\
\bar{I}^{pooled}_{p,f,t}  & = \sum_{s} \mathbb{1}(I_{s,p,f,t} > 0) \cdot q_{s,p,f} \cdot B_{s,p,f,t} \\
\bar{I}^{pooled}_{f,t}    & = \sum_{s,p} \mathbb{1}(I_{s,p,f,t} > 0) \cdot q_{s,p,f} \cdot B_{s,p,f,t}
\end{align}
where $f = 3,4$, $\bar{I}^{pooled}_{s,f,t}$ is the spatially pooled index 
for species $s$, $\bar{I}^{pooled}_{p,f,t}$ is a species pooled index for 
area $p$, $\bar{I}^{pooled}_{f,t}$ is the totally aggregated index (all 
without error), and $\mathbb{1}(I_{s,p,f,t} > 0)$ is the indicator 
function that takes value $1$ when survey $f$ in area $p$ took samples in 
year $t$, and 0 otherwise. Pooled commercial CPUE indices were simulated 
as
\begin{align} 
I^{pooled}_{s,f,t}  & = \frac{\sum_{p} C_{s,p,f,t}}{\sum_{p} E_{p,f,t} } \\
I^{pooled}_{p,f,t}  & = \frac{\sum_{s} C_{s,p,f,t}}{ E_{p,f,t} } \\
I^{pooled}_{f,t}    & = \frac{\sum_{s,p} C_{s,p,f,t}}{ \sum_{p} E_{p,f,t} } \label{eq:endIdx}
\end{align}
where $f = 1,2$, $C_{s,p,f,t}$ is catch, and $E_{p,f,t}$ is commercial trawl 
effort, with subscripts as defined above.

### Target harvest rates and total allowable catch

Simulated harvest decision rules applied a constant target harvest 
rate to generate TACs from one-year ahead biomass forecasts obtained
from each assessment model, i.e.,
\begin{equation}\label{eq:startHR}
TAC'_{s,p,t+1} =  \widehat{U}_{s,p,t} \cdot \widehat{B}_{s,p,t+1},
\end{equation}
where $\widehat{U}_{s,p,t}$ is the estimated target harvest rate for 
species $s$ in stock-area $p$, and $\widehat{B}_{s,p,t+1}$ is the year
$t+1$ biomass forecast from the assessment model applied in year $t$. 
The estimated target harvest $\widehat{U}_{s,p,t}$ was defined to 
incorporate realistic assessment errors in productivity estimates
while simultaneously targeting maximum multi-species yield 
$MSY_{MS,s,p}$. To avoid incorporating technical interactions directly
into the AM dynamics, the target harvest rate scaled
the AM estimate of $\widehat{U}_{MSY,s,p}$ from equation \ref{eq:amBio} 
by the ratio of multi-species and single-species optimal harvest
rates from the operating model, i.e.,
\begin{equation}
\widehat{U}_{s,p,t} =  \widehat{U}_{MSY,s,p} \cdot \frac{U_{MSY,MS,s,p}}{U_{MSY,SS,s,p}}
\end{equation}
where $U_{MSY,MS,s,p},U_{MSY,SS,s,p}$ are the optimal harvest rates 
maximising multi-species and single-species yield, respectively,
taken from the operating model (Table 1), and $\widehat{U}_{MSY,s,p}$ is 
the assesment model estimate of the single-species optimal harvest 
rate applied at time $t$.

Inter-annual increases in TAC were limited to 20\% for all 
individual stocks, i.e.,
\begin{equation}
TAC_{s,p,t+1} = \min \{ TAC'_{s,p,t+1},1.2 \cdot TAC_{s,p,t}\},
\end{equation}
where $TAC'_{s,p,t+1}$ is the proposed TAC determined above, and
$TAC_{s,p,t}$ is the previous year's TAC. This constraint on 
inter-annual TAC changes reflects a constraint on inter-annual changes 
in fishing effort in the objective function used for the omniscient 
manager solutions described below, which is meant to simulate 
gradual investment in additional fishing effort. 

Pooled TACs were set analogously to the stock-specific case above, with 
pooled target harvest rates applied to biomass projections from pooled 
assessments. For a spatially pooled assessment of species $s$, we defined 
the operating model spatially pooled optimal harvest rates as
\begin{align}
U_{MSY,MS,s} &= \frac{\sum_p MSY_{MS,s,p}}{\sum_p B_{MSY,MS,s,p}}, \\
U_{MSY,SS,s} &= \frac{\sum_p MSY_{SS,s,p}}{\sum_p B_{MSY,SS,s,p}},
\end{align}
where the notation is as defined above, with species pooled and 
totally pooled rates defined analogously. For setting TACs under pooled
assessments, the harvest rate scalar from single- to multi-species $U_{MSY}$
in eq 13 used the ratio of pooled $U_{MSY,MS}$ and $U_{MSY,SS}$ values 
defined as in equations 15 and 16. Assessment model estimates of 
pooled optimal harvest rates were then scaled by the ratio of the 
pooled operating model optimal harvest rates.

Pooled TACs were split within an area or across spatial strata proportional 
to Synoptic trawl survey indices for the individual stocks. For example, if 
the TAC for area $p$ is set by a species pooled assessment, then the 
proposed TAC for species $s$ is defined as
\begin{equation}\label{eq:endHR}
TAC'_{s,p,t+1} = \frac{I_{s,p,t^*}}{\sum_{s'} I_{s',p,t^*}} TAC_{p,t+1},
\end{equation}
where $\bar{I}_{s,p,t^*}$ is the most recent individual biomass index 
from the Synoptic survey for species $s$ in area $p$. The most recent
index is used because the synoptic survey alternates between areas each 
year, so not all individual indices are present in a given year.

## Simulation experiments and performance

We ran a total of $15$ simulation experiments comprising five assessment 
models and three data quality scenarios. Simulations integrated over the 
stochastic processess by running a total of 200 random replicates of each 
combination, where each simulation was initialized with the same set of 
random seeds to eliminate random effects among combinations of assessments 
and data scenarios. Assessment convergence was defined as a positive definite 
Hessian matrix and a maximum gradient component less than $10^{-3}$ in 
absolute value. Replicates were considered significant when assessments were 
convergent in 95\% of time steps, chosen to reflect that fitting models 
becomes more difficult as data quantity is deliberately reduced, and a 
simulated assessment can not always be tuned like a real assessment 
performed by a real-life analyst. Results were then calculated
based on the first 100 random seed values that produced significant
replicates for all species and stocks considered. The operating model was run 
for two Dover sole generations [32 years; @seber1997estimation],
because this species had the longest generation time.

Operating model population dynamics were identical among replicates for 
each stock during the operating model historical period, except for the 
last few years near the end, where the operating model simulated
recruitment process errors because they were not estimated in the 
conditioning assessment. Simulated log-normal observation and process 
errors in the projection were randomly drawn with the same standard 
deviations as the errors used in the historical period, and bias corrected 
so that asymptotic medians matched their expected values, i.e., for the 
two fishery independent surveys ($f = 3,4$), the species/area specific
biomass indices were simulated as
\begin{equation}
I_{s,p,f,t} = \bar{I}_{s,p,f,t} \cdot \exp( \tau_{s,p,f} \cdot \delta_{s,p,f,t} - 0.5\tau^2_{s,p,f} ) \\
\end{equation}
where $\bar{I}_{s,p,f,t}$ is the index without error defined
above, $\tau_{s,p,f}$ is the log-normal observation error standard 
deviation, $\delta_{s,p,f,t}$ is the annual standard normal observation 
error residual, and subscripts $s,p,f,t$ are for species, stock, fleet and 
year, respectively. Recruitments are simulated as in appendix A. Error is 
added to survey biomass indices for pooled data independently of the error
added to individual indices, i.e.,
\begin{align}
I_{s,f,t} &= \bar{I}_{s,f,t} \cdot \exp( \tau_{s,f} \cdot \delta_{s,f,t} - 0.5\tau^2_{s,f} ) \\
I_{p,f,t} &= \bar{I}_{p,f,t} \cdot \exp( \tau_{p,f} \cdot \delta_{p,f,t} - 0.5\tau^2_{p,f} ) \\
I_{f,t} &= \bar{I}_{f,t} \cdot \exp( \tau_{f} \cdot \delta_{f,t} - 0.5\tau^2_{f} ) 
\end{align}
where $\tau_{s,f}, \tau_{p,f}, \tau_f$ were averaged over the components
of the pooled index.



### Operating model data quantity scenarios

The three data quantity scenarios ranged from a high to a low quantity
of data by successively removing the earlier CPUE index series from the 
full set, i.e.,

1. **High**-data: Historical CPUE (1956 - 1996), Modern CPUE (1996 onwards), 
Assemblage survey (1984 - 2002, biennial, HSHG only), Synoptic survey 
(2003 onwards, biennial);
2. **Mod**erate-Data: Modern CPUE, Assemblage survey, Synoptic survey;
3. **Low**-Data: Assemblage survey, Synoptic survey.

To improve convergence, the Hierarchical Multi-stock and 
Single-species assessment models were initialised later under the **Mod**
and **Low** data scenarios, with the starting year of the
assessments set to the first year with index data, which was 1984 in
HSHG for both scenario, and 1997 or 2003 for other areas under
the **Mod** and **Low** scenarios, respectively.

### Performance evaluation

#### Omniscient manager simulations

Assessment model performance was measured against a simulated omniscient 
fishery manager who is aware of all the future consequences of harvest
decisions and was, therefore, able to adapt the management to meet specific 
quantitative objectives under any process error conditions 
[@walters1998evaluation]. Omniscient manager solutions were used rather
than equilibrium based metrics [@punt2016management] because most stocks
were in a healthy state in 2016 (i.e. above single-species $B_{MSY}$, 
Table 2) and, therefore, the time-path of fishery development was
important [@walters1988experimental].

The omniscient manager was implemented as an optimisation
of future fishing effort by area (Appendix B), with the objective
function defined as
\begin{equation}
\mathcal{O}  = \left[\sum_{s,p}
                   -\log(\bar{C}_{s,p,\cdot}) \right] + 
                    \mathcal{P}_{diff}\left(\sum_p E_{p,\cdot}\right) +
                    \mathcal{P}_{init}\left(\sum_p E_{p,2017}\right) + 
                    \mathcal{P}_{overfished}\left(B_{s,p,\cdot}\right), 
\end{equation}
where $-\log \bar{C}_{s,p,\cdot}$ is the negative log of total
future catch for species $s$ in area $p$ over the projection period 
(equivalent to maximising catch). Penalty functions $\mathcal{P}$ 
(eq. B.1) were applied for annual changes in total effort across all 
three areas being above 20% ($\mathcal{P}_{diff}$) to match the TAC 
smoother in stochastic experiments, differences greater than 10% 
between the last year of historical effort and the first year $2017$ of 
simulated effort ($\mathcal{P}_{init}$), and a penality when biomass
dropped below a lower threshold of 40\% of single species $B_{MSY,SS}$ 
more than 5\% of time-steps ($\mathcal{P}_{overfished}$). The threshold
of $0.4 B_{MSY,SS}$ is commonly suggested as a limit reference point for 
Canadian fisheries [@DFO2006A-Harvest-Strat], below which the stock could
experience irreparable harm and recruitment could become impaired.

An omniscient manager solution was obtained for each stochastic
trajectory in the stochcastic management simulations. Each replicate was 
run for 80 years to produce several years free of end effects, such as 
transient dynamics at the beginning of the projection, or reduced 
penalties for overfishing at the end of the projection.

#### Cumulative catch loss

For each stochastic trajectory, the cumulative absolute loss 
in catch was calculated  as [@walters1998evaluation]:
\begin{align}
L_{i,s,p} &= \sum_{t = T_1}^{T_2} \vert C_{i,s,p,t,sim} - C_{i,s,p,t,omni} \vert,
\end{align}
where the $C_{i,s,p,t,\cdot}$ values were commercial trawl catch for 
replicate $i$, species $s$, and stock $p$ from stochastic simulations 
($sim$) or the omniscient manager simulation ($omni$) simulation, with 
$C_{i,s,p,t,sim} - C_{i,s,p,t,omni}$ defined simply as catch loss, which
was positive when catch is higher than the omniscient manager's, and negative
when lower. When repeated over all significant random seed values, the loss 
functions generated a distribution of cumulative absolute catch loss, which 
were then used to determine relative performance of each assessment model 
under the three data scenarios. Cumulative absolute catch loss was 
calculated for the ten year period $T_1 = 2028$ to $T_2 = 2037$, chosen in 
the middle of the projection period because dynamics in the earlier period 
were dominated by the smoothers on effort and catch for the omniscient 
manager and TACs, respectively.

A paired analysis was used to determine rank AM configurations across 
species, stocks and replicates. Within each replicate $i$, each AM's 
cumulative absolute catch loss determined the relative rank of each AM 
under a species/stock/OM scenario combination, where lower loss ranked 
higher. Any replicates with less than 95\% convergence rates for any AM 
on any management units were excluded from the aggregate rankings, and any 
species/stock combinations that failed to reach 100 replicates meeting the 
convergence criteria for all AMs were excluded as well, to reduce 
variability in ranking distributions caused by varying sample sizes and 
random seeds. Rankings were then pooled across remaining species and 
stocks within an OM/AM combination, from which the modal rank and average 
rank were calculated.


#### Biomass and overfishing risk

Biomass risk was measured by the probability of stock biomass being below
both 80\% and 40\% of single-species operating model $B_{MSY,SS,s,p}$. The 
threshold of 80\% of $B_{MSY,SS}$ is generally considered to be the level 
where a fish stock transitions from an optimally fished state to an 
overfished state [@hilborn2018measuring], while 40\% of $B_{MSY}$ is 
commonly suggested as a limit reference point for Canadian fisheries, below
which a stock may be considered critically overfished as recruitment may 
become impaired and rebuilding may be required [@DFO2006A-Harvest-Strat]. 
For both biomass levels, the probability was calculated as
\[
P(B_{s,p,t} < \lambda B_{MSY,SS,s,p} ) = \frac{1}{3200} \sum_{i = 1}^{100}\sum_{t = 2016}^{2047} \mathbb{1}(B_{i,s,p,t} < \lambda B_{MSY,SS,s,p})
\] 
where $i,s,p,t$ are replicates meeting the 95\% convergence criteria, 
species, stocks and time steps, respectively, $\lambda = 0.4,0.8$, 
and $\mathbb{1}$ is the indicator function that takes value $1$ when 
its argument is true, and zero otherwise. Overfishing risk was similarly 
calculated as the probability of fishing mortality exceeding single-species 
operating model $F_{MSY,SS,s,p}$.


## Sensitivity analyses

Parameter prior distributions area a key feature of most contemporary
stock assessment models, even in data-rich contexts. Moreover, prior
distributions are a defining feature of hierachical multi-species
stock assessment models. Therefore, we focused most sensitivity analyses 
on fixed prior standard deviations for AM leading  parameters $MSY$ 
and $U_{MSY}$, and the hierarchical shrinkage prior SDs $\tau_q$ and
$\sigma_{U_{MSY}}$ (Table 4). Sensitivity of performance to future 
increases in fishery independent survey precision was tested, where 
the Synoptic survey observation error variance was reduced with a 
linear ramp-down over the first 5 years of the projection period to 
simulate a gradual increase in survey effort.


