# Results

```{r loadInfoFiles, echo = FALSE, include = FALSE, warning = FALSE}
# Now read in all the info files
info.df <- readBatchInfo(batchDir = projDir) %>%
      mutate( blobPath = "", 
              perfTabPath = "", 
              lossBlobPath = "" )
# Update paths for each RData file and perf 
# table file
for( simIdx in 1:nrow(info.df))
{
  simLabel <- info.df$simLabel[simIdx]

  info.df$blobPath[simIdx]     <- file.path(projDir, simLabel, paste(simLabel,".RData",sep = "") )
  info.df$perfTabPath[simIdx]  <- file.path(projDir, simLabel, "simPerfStats.csv" )
  info.df$lossBlobPath[simIdx] <- file.path(projDir, simLabel, "loss.RData" )
}


```


## Omniscient Manager Performance


As expected, the omniscient manager was able to achieve the theoretical 
multi-species optimal yield in the presence of technical interactions during
the middle of the projection period (Figure 4, blue closed circle). Median 
biomass, catch, and fishing mortality reach the equilibrium after a transition 
period of about 20 years. During the transitionary period, effort is slowly 
ramped up in each area from the end of the historical period, stabilising 
around area-specific $E_{MSY}$ after about 12 years (Figure 5, blue closed 
circles). As is common when maximising catch over a finite time horizon, 
a reduction in biomass and an increase in effort was observed towards the end 
of the 80 year projection period, where penalties from lower biomasses and 
overfishing the stock relative to the multi-species optimal harvest 
rate are lower than the catch increases; however, the omniscient manager 
avoids a complete crash of the complex thanks to the penalty on avoiding the 
critically overfished state at 40\% of single-species $B_{MSY,SS}$.

Each area had similar relationships between single-species and multi-species
optimal biomass levels, with one species overfished, one underfished, and one
close to optimally fished, relative to single-species reference points. In 
HSHG and QCS, the overfished stocks were both Rock sole, fished down to 
74\% (HSHG) and 81\% of $B_{MSY,SS}$ to increase fishery access to Dover and 
English soles in those areas (Table 1). In WCVI, English sole was slightly 
overfished relative to single-species at 91\% of $B_{MSY,SS}$, but this 
would be of little concern in a real fishery if the absolute size were
not so small. Despite the tendency of the omniscient manager toward 
overfishing at least one species in each area, very few optimal solutions 
risked severe overfishing below 40\% of $B_{MSY}$ (Table 3), indicating that 
lost yield from more intense overfishing relative to single-species
optimal levels is not compensated by increased harvest from other species,
which are sometimes larger populations with higher TACs. The probability 
of being critically overfished in the period 2028 - 2037 was 1\% for 
English and Rock sole stocks, and 0\% for all Dover sole stocks.

Although DER stocks begin the simulations in an overall healthy state, 
the omniscient manager reduced fishing effort to 0 in all areas early in 
the projection period in some replicates (Figure 5, 2016-2020). In these 
cases, anticipatory feedback control by the omniscient manager reduced 
fishing effort to avoid low spawning stock biomasses, thus ensuring higher 
production in later time steps where recruitments were lower than average
for sustained periods.

## Assessment model performance

### Rankings by catch loss

Due to low convergence rates for HSHG and QCS Rock sole and WCVI Dover 
sole in the High scenario, and WCVI Rock sole under the Mod 
scenario (Figure S1), results from those management units are excluded 
from catch loss rankings.

Hierarchical Multi-species assessment models ranked highest under all 
data quantity scenarios (Table 4). Under the Low data 
quantity scenario, the Hierarchical model had the lowest cumulative absolute 
catch loss in over 40\% of replicate/stock/species combinations (Figure 6), 
ranking highest by average and modal rank in the aggregate. When split
across individual species/areas, the modal rank for the hierarchical AM
remained at 1, but there was more variability in the ranking distributions
in the HSHG area (e.g. Dover sole), leading to a drop in average rank 
(Figure S1, online supplement). As data quantity increased for the Mod 
scenario, the modal rank and average rank of the hierarchical model 
remained the highest out of all AMs in the aggregate, ranking 1st in just
under 40% of cases (Figure 6), while the variability in rankings in the 
HSHG area increased (Figure S1), pushing the average rank a littler
lower than under the Low scenario. Results under the High scenario 
were similar to the Mod scenario, where the Hierarchical model was ranked
first in about 40\% of cases, and a slightly higher average rank than the 
Mod scenario, driven largely by a reduction in catch loss for WCVI English 
sole (Figure S1).

When ordered by average rank, Species Pooling AMs came second after 
the hierarchical AMs under all data quantity scenarios (Table 4).
Under the High data quantity scenario, the the data pooling methods ranked 
highest in both modal and average ranks (Table 4, High). Total and Spatial 
Pooling methods performed similarly under the High scenario, with
only a small difference between average ranks, but quite different 
rank distributions, where Spatial pooling catch loss rankings were 
almost uniformly distributed, but Total pooling ranks had a clear mode
in 4th place (Figure 6, High scenario), which was reflected in individual 
stock rank distributions (Figure S1). The Total Pooling AM's 4th place 
rank was observed in around 40\% of cases in the aggregate (Figure 6), 
and was also the modal rank for most individual stock distributions (Figure 
S1). As data were removed for the Mod data quantity scenario, the Spatial
Pooling AM dropped from 3rd to 4th place, driven largely by increased
catch loss in the QCS area. The Single-species method had the 
worst rank under all data quantity scenarios, with a consistent modal rank 
of 5th across all scenarios (Figure 6), with most consistently inferior 
performance observed under the High data quantity scenario, where the 
average rank was 4.63 (Table 4).

Choke effects both increased and reduced catch loss, depending
on the assessment errors. On the one hand, there were several cases
where AM underestimates of biomass and/or productivity produced TACs 
that produced a realised harvest rate much lower than the target associated 
with maximum multi-species yield. This behaviour was most prominent under 
Single-species AMs for the Low and Mod scenario, where the fished 
initialisation led the AMs to estimate a larger and less productive stock
in equilibrium, estimating a steep early decline in biomass followed by 
apparent equilibration to a low biomass state where catch balances production 
(Figure 7), producing very low TACs despite the large positive error in 
unfished biomass. Low TACs of more catchable species constrained the TACs of 
the remaining species, increasing catch loss across the whole complex 
(Figure 8). On the other hand, when TACs pushed harvest rates very close 
to the target level, choke effects could reduce catch loss by constraining 
TACs that were too high compared to the target, protecting against overfishing
relative to the multi-species harvest rate. These "protective" choke
effects were observed under the pooling AMs and the hierarchical AM,
and occured even when there were large assessment errors. For example, under 
the hierarchical AM in the Mod scenario, AMs perceived a larger and less 
productive stock than the OM, similar to the Single-species AM, but shrinkage
priors on productivity parameters were able to reduce the magnitude of 
the error in $U_{MSY}$ so that, despite having some of the largest errors
in biomass forecasts and the $B_{MSY}$, the AM did not perceive a stock that 
quickly declined from its high initial biomass (Table S2). Biomass estimates 
were then positively biased with respect to the operating model biomass, which 
were compensated by the negatively biased productivity estimates, producing 
more appropriately scaled TACs for all stocks, with choke effects occasionally 
protecting against overfishing. More optimal TACs then reduced catch loss 
overall, with median catch loss close to zero for the 2028 - 2037 period 
(Figure 10).



### Biomass and overfishing risk

There was little chance of any stock being in an overfished state under 
any data scenario and AM combination (Table 4). No AM pushed stocks into 
a critically overfished state where $B_{s,p,t} < 0.4 B_{MSY,SS,s,p}$ under 
the High and Mod data scenarios, while under the Low scenario a small 
probability of being critically overfished was observed under the Species 
Pooling (max 1\%) and Spatial Pooling (max 6\%) AMs. As expected, there 
were higher probabilities of being overfished 
($B_{s,p,t} < 0.8 B_{MSY,SS,s,p}$) under all scenarios,
with the highest observed at 22\% under the Spatial Pooling AM and Low 
scenario. The Single-species AM rarely pushed any stock into an over-fished
state under any data scenario, as biomass was usually underestimated for at 
least one species in each area, producing a choke constraint and higher 
catch loss as discussed above.

As expected, there was a higher risk of overfishing relative to 
single-species optimal fishing mortality rates $F_{MSY,SS,s,p}$ when
attempting to maximise multi-species catch. Under the High and Mod
scenario, Spatial Pooling and Single-species AMs were the only
AMs with positive probabilities across the entire DER complex, with
Spatial Pooling AMs overfishing more often. Unsurprisingly, overfishing 
was observed under all AMs for the Low scenario, reflecting the greater 
difficulty in estimating species productivity with low power data. Similar
to the other scenarios and biomass risk above, the Spatial Pooling AM 
exceeded $F_{MSY,SS}$ more often (max 50\%), while the Single-species AM
was the most conservative given that it often underestimated biomass
and caused choke constraints (max 1\%). Hierarchical AMs were moderate 
compared to the other AMs, falling in the middle of the pack and 
exceeding $F_{MSY,SS}$ in 14\% of years on average (max 29\%).



### Catch-Biomass trade-offs

Distributions of catch and biomass relative to $MSY_{SS}$ and
$B_{MSY,SS}$, respectively, were produced for the time
period $2028 \leq t \leq 2037$ for each assessment model and Scenario
combination. The medians of those relative catch and biomass 
distributions were visually compared to each other and to the 
central 95\% of the omniscient manager's trajectories over the 
same time period (Figure 11) in order to understand the biomass and 
catch trade-offs between different model choices.

The Hierarchical Multi-species assessment model median catch between 2028 
and 2037 came closest (i.e., smaller Euclidean distance) to the omniscient 
manager median catch under the Low data quantity scenario outside the HSHG 
area, and for HSHG Dover sole (Figure 11, compare points to the horizontal 
segment in black crosshair). For HSHG English and Rock soles, while the 
Hierarchical model tended to take a little more catch than the omniscient 
manager under the Low scenario, a large biomass surplus relative to the 
omniscient manager was present, indicating that realised harvest rates 
from TACs set by the hierarchical AM were smaller than those set by the 
omniscient manager.

Although the range of biomass-catch trade-offs were quite broad for each 
stock, the majority of Scenario/AM combinations lie inside the central 
95\% distributions of the omniscient manager (Figure 11, black crosshairs). 
Notable exceptions to this were the Single-species models for all 
species/areas under the High scenario and in HSHG under the Low scenario
for Dover and English, the Hierarchical models in QCS and WCVI under the 
High scenario, and the Total Pooling method for WCVI Rock sole under the 
High data quantity scenario. As described above, the Single-species methods 
tended to under-estimate biomass and productivity under the Low scenario, 
so the tendency of the Single-species median biomass-catch to be towards the 
lower right corner of the range is expected. For the Single-species and 
Hierarchical methods under the High scenario, the reason is a combination 
of large negative assessment errors in some or all years for choke species, 
and the 20\% limit on increases in catch, producing a low-catch/high-biomass
dynamic. Finally, the Total Pooling outlier in WCVI Rock Sole is caused by 
a persistent small negative assessment error, and an underallocation of the 
pooled TAC to WCVI Rock thanks to the differing Synoptic survey 
catchabilities. The Total Pooling method was also outside the central
95\% of the omnisceint manager in HSHG under the High scenario, but only 
marginally so. 

Catch-biomass trade-offs were approximately collinear under both
High and Low data quantity scenarios for all stocks. All spawning 
stock biomasses were well above both the single-species 
and multi-species optimal levels at the beginning of the projection 
period (e.g., Table 1, Stock Status), meaning that the catch limits 
set by all methods were depleting a standing stock and benefited from 
its surplus production. Under these conditions, an increase in catch 
almost linearly caused a decrease in biomass as the compensatory 
effect of density dependence was minimal. 

During the 2027 - 2036 period, median catch and biomass under the 
omniscient manager were higher than the optimal levels for both the 
multi-species and single-species maximum yield (green diamond 
crosshair and blue circle, respectively, Figure 11). As discussed
above, this is because the transitionary period from fishery development 
to equilibrium dynamics is takes about 20 years under the omniscient
manager. While catch is higher than MSY during the development period,
this is not necessarily overfishing as the biomass also higher than
$B_{MSY}$; however, there was overfishing relative to single-species
$F_{MSY}$ occured for all stocks under the omniscient manager, and, 
as expected, with higher probability for all stocks where
$B_{MSY,MS} \leq B_{MSY,SS}$ (Table 3).





## Sensitivity of results to prior standard deviations

We summarised average model sensitivities by fitting linear regressions to 
the distributions of median cumulative absolute catch loss (Figure 12). To 
remove the effect of absolute catch scales on the regressions, median loss 
distributions were standardised across assessment models, stratified by 
species, stock-area, and data scenario. Regressions with positive slopes 
had increasing catch loss with increasing uncertainty, and negative 
or zero slopes indicated a decrease or no change in catch loss with 
increasing prior uncertainty. Linear model slope parameter $p$-values 
for each AM were also calculated to determine if an effect was significant 
or not, where we define significance as $p < 0.1$.

While all AMs except the Total Pooling AM were slightly sensitive to $MSY$
prior CVs under the high scenario, there was no change in the relative
rankings of the AMs (Figure 12, first column). Under the Low scenario, 
only the Single-species and Species Pooling AMs were sensitive to $MSY$ 
CVs, with catch loss dropping about a standard deviation as CVs decreased
from 1.0 to 0.1 for both AMs, with Species Pooling AMs moving from
fourth to second lowest mean catch loss, but the relative ranking of all
other AMs remained the same.

Hierarchical and Single-species AMs were sensitive to the $U_{MSY}$ prior 
standard deviation under both scenarios, and the Species Pooling AM
was also sensitive under the Low scenario (Figure 12, second column, 
$p > 0.05$). However, under the High scenario, no sensitivity led to a 
change in ranking for any AMs over the range of $U_{MSY}$ prior standard 
deviations tested, as most AMs showed a catch loss change of less than
0.5 standard deviations, except for the Single-species AM, which
was again an outlier. Under the Low scenario, the Total Pooling
and Single-species AMs remained at the bottom of the rankings, despite
a decrease off around 1.5 standard deviations for the Single-species AM.
At the same time, Spatial Pooling, Species Pooling, and Hierarchical AMs 
catch losses under the Low scenario appeared to converge as prior 
standard deviations increased from 0.1 to 1.0. 


Interestingly, the Hierarchical Multi-species assessment models reacted 
differently to changing catchability and $U_{MSY}$ hierarchical shrinkage 
priors under the High and Low scenarios (Figure 12, third column). As 
$\sigma_{U_{MSY}}$ and $\tau_q$ increased from 0.1 to 0.5, average catch 
loss increased by about 1 standard deviation under the High scenario 
($p < 0.01$), mostly driven by assessment errors in the QCS and WCVI areas,
leading to a widening range of catch trajectories as hierarchical prior
standard deviations increased. Under the Low scenario, median absolute 
catch-loss dropped by about 1 standard devation, indicating that TACs were 
closer to the omniscient manager as hyper-prior SDs increased. The improved 
performance with increasing hyper-prior uncertainty was caused by a 
combination of subtle effects, with some assessments becoming more biased, 
and others less biased, which occasionally switched the choke species in an 
area. The combination of raised and lowered catch limits and technical 
interactions produced beneficial choke effects, reducing catch loss overall.

Finally, there was low sensitivity to the reduction in Synoptic survey
standard errors (Figure 12, fourth column). Under the High scenario, the 
all but the Spatial Pooling AM had significant improvements of 
around 0.3-0.5 standard deviations with decreasing standard error 
($p < 0.05$), while the Spatial pooling had a non-significant change 
($p = 0.18$). Under the Low scenario, only the Species Pooling AM catch 
loss improved significantly, dropping around 0.25 standard deviations with
decreasing Synoptic survey standard error ($p < 0.01$), and switching places
with the Hierarchical AM for the lowest average catch loss. For both 
scenarios, the decreases in catch loss appear to be caused by a 
slight improvement in pooled TAC allocation with increased survey 
precision, but choke constraints were still present.


