# Tables

```{r loadInfoFiles-tables, echo = FALSE, include = FALSE, warning = FALSE}
# Now read in all the info files
info.df <- readBatchInfo(batchDir = projDir) %>%
      mutate( blobPath = "", 
              perfTabPath = "", 
              lossBlobPath = "" )
# Update paths for each RData file and perf 
# table file
for( simIdx in 1:nrow(info.df))
{
  simLabel <- info.df$simLabel[simIdx]

  info.df$blobPath[simIdx]     <- file.path(projDir, simLabel, paste(simLabel,".RData",sep = "") )
  info.df$perfTabPath[simIdx]  <- file.path(projDir, simLabel, "simPerfStats.csv" )
  info.df$lossBlobPath[simIdx] <- file.path(projDir, simLabel, "loss.RData" )
}

.loadSim( 2, folder = params$groupFolder)
```

```{r loadOmni-tables, echo = FALSE, include = FALSE, warning = FALSE}
# load performance table
omniPerfTab <- read.csv("./data/omniPerfTable.csv", header = TRUE, stringsAsFactors = FALSE )


```

```{r loadHistoryFit, echo = FALSE, include = FALSE, warning = FALSE}
fitReport <- .loadFit(params$history)

nS <- fitReport$repOpt$nS
nP <- fitReport$repOpt$nP
nG <- fitReport$repOpt$nG

```



```{r tableCaps, echo = FALSE, include = FALSE, warning = FALSE }
dataSourceCap <- "Fishery dependent and independent indices of 
biomass available for stock assessments of DER complex species."

stockStatusTabCap <- "Unfished biomas $B_0$, single-species MSY based 
reference points $B_{MSY,SS}$ and $U_{MSY,SS}$, stock status as absolute
biomass in 2016 $B_{2016}$, depletion relative to single-species
optimal biomass $B_{2016}/B_{MSY,SS}$, and commercial trawl 
catchability scalar $q^{F}$ for all DER complex stocks in 2016."

expDesignTableCap <- "Summary of OM scenario and AM structure factors 
in the experimental design for the simulation experiments."

AMpriorTableCap <- "Prior distributions used for each assessment
model. For single stock and hierarchical multi-stock assesssment
models, $s_f$ is 1 for commercial indices, and 0.5 for survey
indices."

sensRunTableCap   <- "Summary of sensitivity analyses, showing
the total number of experiments, the factor being varied, the
levels of that factor, and the data scenarios and AMs included
in the analysis."

omniPerfTabCap <- "Probability of being overfished and experiencing
overfishing with respect to single-species reference points, and 
catching less than the historical miniumum during the time period
2028 - 2037 for all nine DER complex stocks when managed by the 
omniscient manager."

AM_relErrorsTabCap <- "Bias and precision metrics (MRE, MARE) for assessment 
model estimates under the Rich data scenario. Metrics were calculated for 
spawning stock biomass $B_t$, assessment model 
$B_{MSY}$, and assessment model $U_{MSY}$. Operating model $B_{MSY}$
for pooled data AMs was defined by pooling optimal biomass for
component stock, and operating model $U_{MSY}$ was found by pooling 
single-species maximum yield, and taking the ratio of pooled yield
and biomass."

lossRankTabCap <- "Summary of AM rankings with respect to cumulative
absolute catch loss between 2026 and 2035 under each scenario. The
rank column shows the average rank of the AMs over all species/areas,
and the range of that distribution in parentheses. AMs are ordered by
mean rank within a scenario."


```


```{r dataSources, echo = FALSE, warning = FALSE}

dataSourcesTable <- tibble::tribble( 
~Series,             ~Extent,           ~Description,
"Historical Commercial",         "1976 - 1995",     "Historical period commercial CPUE",
"Modern Commercial",          "1996 - 2016",     "Modern period commercial CPUE",
"HS Assemblage",             "1984 - 2002",     "Hecate Strait Assemblage trawl survey biomass index, biennial",
"Synoptic",               "2003 - 2016",     "Multi-species Synoptic trawl survey biomass index, biennial",
)

kable(  dataSourcesTable, escape = FALSE,
        booktabs = TRUE,
        caption = dataSourceCap,
        align = rep("l",ncol(dataSourcesTable))) %>%
  kable_styling(latex_options = c("striped", "hold_position","scale_down"),
                bootstrap_options = c("striped", "hover"))

```

\clearpage


```{r stockStatusTab, echo = FALSE, warning = FALSE }
stockStatusColNames <- c( "Species",
                          "Stock",
                          "B0",
                          "Bmsy",
                          "Umsy",
                          "$B_{2016}$",
                          "$B_{2016}/B_{MSY}$",
                          "qF" )

stockStatusTab <- matrix( NA, nrow = 9, ncol = length(stockStatusColNames) )
colnames(stockStatusTab) <- stockStatusColNames
stockStatusTab <- as.data.frame(stockStatusTab)

specLabs  <- fitReport$species
stockLabs <- fitReport$stocks

B0_sp     <- fitReport$repOpt$B0_sp
refPts    <- fitReport$repOpt$refPts$FmsyRefPts

# spawning biomass series
SB_spt    <- fitReport$repOpt$SB_spt
D_sp2016  <- SB_spt[,,"2016"] / refPts$BeqFmsy_sp

# Pull qF
.loadSim( 2, folder = params$groupFolder)
qF_sp      <- blob$om$qF_ispft[1,,,2,blob$om$tMP]

for( s in 1:nS )
  for( p in 1:nP )
  {
    rIdx <- p + (s-1)*nP

    stockStatusTab[rIdx,"Species"]    <- specLabs[s]
    stockStatusTab[rIdx,"Stock"]      <- stockLabs[p]

    # Pull reference points, B0
    stockStatusTab[rIdx,"B0"]         <- round(B0_sp[s,p],2)
    stockStatusTab[rIdx,"Bmsy"]       <- round(refPts$BeqFmsy_sp[s,p],2)
    stockStatusTab[rIdx,"Umsy"]       <- round(refPts$Umsy_sp[s,p],2)
    stockStatusTab[rIdx,"$B_{2016}$"] <- round(SB_spt[s,p,"2016"],2)
    stockStatusTab[rIdx,"$B_{2016}/B_{MSY}$"] <- round(D_sp2016[s,p],2)
    stockStatusTab[rIdx,"qF"]         <- round(qF_sp[s,p],3)

  }

colnames(stockStatusTab) <- c(  "Species",
                                "Stock",
                                "$B_0$",
                                "$B_{MSY,SS}$",
                                "$U_{MSY,SS}$",
                                "$B_{2016}$",
                                "$B_{2016}/B_{MSY,SS}$",
                                "$q^{F}$")

stockStatusTab <- stockStatusTab[,-1]

kable(  stockStatusTab, escape = FALSE, 
        caption = stockStatusTabCap, booktabs = T,
        align = rep("c",ncol(stockStatusTab))) %>%
  kable_styling(latex_options = c("striped", "scale_down","hold_position"),
                bootstrap_options = c("striped", "hover")) %>%
  pack_rows( "Dover sole",1,3 ) %>%
  pack_rows( "English sole",4,6 ) %>%
  pack_rows( "Rock sole",7,9 ) %>%
  add_header_above(c(" " = 1, "Single-species Reference Points" = 3, "Stock Status" = 2, "Comm. Catchability" = 1 ))

```


\clearpage

<!-- ```{r expDesignTab, echo = FALSE, warning = FALSE}

options(knitr.kable.NA = "")

expFactorLabelsTable <- tibble::tribble( 
  ~Factor,     ~Description,
  "Rich",       "Historical and modern commercial indices,",
  NA,           "with Assemblage and Synoptic survey indices",
  "Mod",      "Modern commercial index only, with",
  NA,           "Assemblage and Synoptic survey indices",
  "Poor",       "Assemblage and Synoptic survey indices, with",
  NA,           "no commercial indices",
  "Total Aggregation",         "One assessment model fit to totally aggregated data",
  NA,NA,
  "Spatial Pooling",    "Three independent assessments fit to spatially pooled data",
  NA,           "for each DER complex species",
  "Species Pooling",    "Three independent assessments fit to species pooled data",
  NA,           "in each DER complex stock area",
  "Hierachical Multi-stock",        "One joint hierarchical multi-stock assessment of",
  NA,           "all nine DER complex stocks",
  "Single-stock",         "Nine independent single-stock assessments of",
  NA,           "each DER complex stocks",)

colnames(expFactorLabelsTable) <- c("Level","Description")

kable(  expFactorLabelsTable, escape = FALSE,
        booktabs = TRUE,
        caption = expDesignTableCap,
        align = rep("l",ncol(expFactorLabelsTable))) %>%
  kable_styling(latex_options = c("striped", "hold_position","scale_down"),
                bootstrap_options = c("striped", "hover")) %>%
  pack_rows("OM Data Scenario", 1, 6) %>%
  pack_rows("AM Structure", 7, 16)


``` -->


```{r AMpriorTab, echo = FALSE }

options(knitr.kable.NA = "")

AMpriorTable <- tibble::tribble( 
  ~AM,                           ~VariableName,      ~Prior,
  "Data-Pooled AMs",             "$B_{MSY}$",        "$B_{MSY} \\sim N(m_{B_{MSY}}, 0.2 \\cdot m_{B_{MSY}})$",
  NA,                            "$U_{MSY}$",        "$\\log U_{MSY} \\sim N(m_{\\log U_{MSY}}, 0.4)$",
  NA,                            "$q_{f}$",          "$\\log q_{f} \\sim N(m_{\\log q_{f}}, 1.0)$",
  "Single-stock AM",             "$B_{MSY,s,p}$",    "$B_{MSY,s,p} \\sim N(m_{B_{MSY}}, 0.1 \\cdot m_{B_{MSY}})$",
  NA,                            "$U_{MSY,s,p}$",    "$\\log U_{MSY,s,p} \\sim N(m_{\\log U_{MSY}}, 0.1)$",
  NA,                            "$q_{s,p,f}$",      "$\\log q_{s,p,f} \\sim N(m_{\\log q_{s,p,f}}, s_f)$",
  "Hierarchical Multi-stock AM", "$B_{MSY,s,p}$",    "$B_{MSY,s,p} \\sim N(m_{B_{MSY}}, 0.2 \\cdot m_{B_{MSY}})$",
  NA,                            "$U_{MSY,s,p}$",    "$\\log U_{MSY,s,p} \\sim N(\\log \\overline{U}_{MSY,s}, \\sigma_{U_{MSY}})$",
  NA,                            "$U_{MSY,s}$",      "$\\log \\overline{U}_{MSY,s} \\sim N(\\log \\overline{U}_{MSY}, \\sigma_{U_{MSY}})$",
  NA,                            "$U_{MSY}$",        "$\\log \\overline{U}_{MSY} \\sim N( m_{\\log U_{MSY}}, .4)$",
  NA,                            "$q_{s,p,f}$",      "$\\log q_{s,p,f} \\sim N(\\log \\overline{q}_{s,f}, \\tau_q)$",
  NA,                            "$q_{s,f}$",        "$\\log \\overline{q}_{s,f} \\sim N( m_{\\log q_{s,f}}, s_f)$",
  "Process errors",              "$\\zeta_{s,p,t}$", "$\\zeta_{s,p,t} \\sim N(0,0.05)$", )


colnames(AMpriorTable) <- c("AM","Variable","Prior")

AMpriorTable <- AMpriorTable[,-(1:2)]

kable(  AMpriorTable, escape = FALSE,
        booktabs = TRUE,
        caption = AMpriorTableCap,
        align = rep("l",ncol(AMpriorTable))) %>%
  kable_styling(latex_options = c("striped", "hold_position"),
                bootstrap_options = c("striped", "hover")) %>%
  pack_rows("Data-pooled AMs", 1, 3) %>%
  pack_rows("Single-stock AM", 4, 6) %>%
  pack_rows("Hierarchical multi-stock AM", 7, 12) %>%
  pack_rows("All AMs", 13, 13)

```

\clearpage{}

```{r sensRunsTable, echo = FALSE}
sensRunTable <- tibble::tribble( 
    ~N,     ~Factor,                ~Levels,            ~Scenarios,     ~AMs,
    30,     "$B_{MSY}$ prior CV",   "$0.1, 0.5, 1.0$",  "Comm1, Surv",  "All",
    30,     "$U_{MSY}$ prior SD",   "$0.1, 0.5, 1.0$",  "Comm1, Surv",  "All",
    6,      "$\\tau_q$, $\\sigma_{U_{MSY}}$", "$0.1, 0.2, .5$",   "Comm1, Surv","Hierarchical only", )

kable(  sensRunTable, escape = FALSE,
        booktabs = TRUE,
        caption = sensRunTableCap,
        align = rep("l",ncol(sensRunTable))) %>%
  kable_styling(latex_options = c("striped", "hold_position","scale_down"),
                bootstrap_options = c("striped", "hover")) 
```

\blandscape

```{r omniPerfTab, echo = FALSE, warning = FALSE}
omniPerfTab <- omniPerfTab %>%
                mutate( "pBtLt.4Bmsy" = 1-pBtGt.4Bmsy,
                        "pBtLt.8Bmsy" = 1-PBtGt.8Bmsy ) %>%
                dplyr::select(  Species = species,
                                Stock = stock, 
                                "pBtLt.4Bmsy",
                                "pBtLt.8Bmsy",
                                pCtGtMSY,
                                pFtGtFmsy,
                                pHistLowCatch )

colnames(omniPerfTab) <- c( "Species",
                            "Stock",
                            "$P(B_t < .4B_{MSY,SS})$",
                            "$P(B_t < .8B_{MSY,SS})$",
                            "$P(C_t > MSY_{SS})$",
                            "$P(F_t > F_{MSY,SS})$",
                            "$P(C_t < \\min C_{1951:2016})$")


omniPerfTab <- omniPerfTab[,-1]

kable(  omniPerfTab, escape = FALSE, 
        caption = omniPerfTabCap, booktabs = T,
        align = rep("c",ncol(omniPerfTab))) %>%
  kable_styling(latex_options = c("striped", "scale_down","hold_position"),
                bootstrap_options = c("striped", "hover")) %>%
  pack_rows( "Dover sole",1,3 ) %>%
  pack_rows( "English sole",4,6 ) %>%
  pack_rows( "Rock sole",7,9 ) %>%
  add_header_above( c(" " = 1,
                      "Prob. of being overfished" = 2,
                      "Prob. of overfishing" = 2,
                      "Prob. of low catch" = 1) )

```

\elandscape

\clearpage

<!-- ```{r AMmareTable, echo = FALSE }

mareTable <- read.csv(here::here("Outputs",params$groupFolder,"mareTable.csv"))

round2 <- function(x)
{
  x <- round(x,2)
  x
}

# Replace Scenario names and AM names
AMlabs <- c(  "singleStock_omF_MSrefPts"= "SS",
              "hierMultiStock_omF_MSrefPts"= "HMS",
              "speciesPooling_omF_MSrefPts"= "SpePool",
              "spatialPooling_omF_MSrefPts"= "SpaPool",
              "totalAgg_omF_MSrefPts"= "TA")
scenLabs <- c(  "DERfit_HcMcAsSsIdx" = "Comm1",
                "DERfit_McAsSsIdx" = "Comm2",
                "DERfit_McSsIdx" = "Comm3",
                "DERfit_AsSsIdx"  = "Surv")

mareTable <- mareTable %>%
                  mutate( Scenario = stringr::str_replace_all(Scenario, scenLabs),
                          AM = str_replace_all(AM, AMlabs) ) %>%
                  dplyr::select( Scenario, AM, Species, Stock, MARE_Bt, MRE_Bt, MARE_Bmsy, MRE_Bmsy, MARE_Umsy, MRE_Umsy ) %>%
                  filter( Scenario == "Comm2" ) %>%
                  arrange(Scenario, AM, Species) %>%
                  mutate_if(is.numeric, round2 )


kable(  mareTable, escape = FALSE, 
        caption = AM_relErrorsTabCap, booktabs = T,
        align = rep("c",ncol(mareTable))) %>%
  kable_styling(latex_options = c("striped", "scale_down","hold_position"),
                bootstrap_options = c("striped", "hover")) 

```

\clearpage -->

```{r lossRankTable, echo = FALSE, warning =FALSE}
lossRankTable <- makeLossRankTable( groupFolder = params$groupFolder,
                                    prefix = "parBat",
                                    period = 73:82,
                                    clearBadReps = TRUE,
                                    minSampSize = 10 ) %>%
                    ungroup()

# Replace Scenario names and AM names
AMlabs <- c(  "singleStock"= "Single Stock",
              "hierMultiStock"= "Hierarchical Multi-stock",
              "speciesPooling"= "Species Pooling",
              "spatialPooling"= "Spatial Pooling",
              "totalAgg" = "Total Aggregation")
scenLabs <- c(  "DERfit_HcMcAsSsIdx" = "Rich",
                "DERfit_McAsSsIdx" = "Mod",
                "DERfit_AsSsIdx"  = "Poor")

lossRankTable <- lossRankTable %>%
                  mutate( Scenario = stringr::str_replace_all(Scenario, scenLabs),
                          AM = str_replace_all(AM, AMlabs) ) %>%
                  filter( Scenario %in% c("Rich","Mod","Poor")) %>%
                  arrange(match(Scenario, c("Rich", "Mod", "Poor")),
                            absCrank) %>%
                  dplyr::select( Scenario, AM, absCrank )
                  


colnames(lossRankTable) <- c( "Scenario","AM",
                              "Average Loss Rank (range)")

kable(  lossRankTable[,-1], escape = FALSE, 
        caption = lossRankTabCap, booktabs = T,
        align = rep("c",ncol(lossRankTable[,-1]))) %>%
  kable_styling(latex_options = c("striped", "hold_position"),
                bootstrap_options = c("striped", "hover")) %>%
  pack_rows( "Rich",1,5 ) %>%
  pack_rows( "Mod",6,10 ) %>%
  pack_rows( "Poor",11,15 ) 
```

\clearpage