\clearpage

# (APPENDIX) Appendices {-}

# Appendix A: The operating model

Our operating model was based on an age- and 
sex-structured, multi-species and multi-stock population
dynamics model. We simulated the species and stocks
assuming no ecological interactions or movement
between areas. This assumption is unrealistic,
but it is how the stocks are currenly managed
so we decided that this was the best place to begin
our management simulation.



# Appendix B: Surplus production assessment model

We defined our multi-species, multi-stock surplus 
production stock assessment model as an extension 
of a model that was the subject of a previously
published sensitivity analysis of hierarchical
surplus production models [@johnson2018evaluating].
Because this model was previously published, we
only discuss the differences between the version
we used in this paper and version in the previous 
publication.

The full model is described in Table B1. 
As in the equations in the main body of this paper, 
we denote species by a subscript $s$, stock areas 
by a subscript $p$ (population), and observation series from 
different fleets by a subscript $f$ 
for all equations in Table B1.

The following list is all the extensions from the 
original model to the AM used in this paper, with
references to Table B1 in parentheses:

1. An additional shrinkage prior on Umsy_sp across
species (Equation XX)
2. Initial biomass prior for tuning purposes (Eq. XX)
3. All variance parameters were fixed for tuning
simulated MP performance

We fixed all variance parameters of the stock assessment 
model during closed loop simulations. This was required
to improve stability of the assessments during closed loop
simulations with limited data, and also allowed us 
to tune the performance of the management procedure.

For the two time series of commercial CPUE observations, 
we calculated the conditional maximum likelihood estimate
of fleet catchability (eq O.2)



```{r, echo = FALSE, warnings = FALSE, include = FALSE}
# Read in table of AM equations here.

cat("Insert AM table of equations here\n")

# AMeqTab <- tibble::tribble(
#   ~Eq.no,      ~Definition,
#   "B.1",       "$B_{s,p,t_0} = \left\{\begin{array}{ll} B_{s,p,0} & t_0 = 1 \\ B_{s,p,init} & t_0 > 1 \end{array} \right.",
#   "B.2",       "$B_{s,p,t} = (B_{s,p,t-1} + r_{s,p} \cdot B_{s,p,t-1} \cdot (1 - \frac{B_{s,p,t-1}}{B_{s,p,0}}) - C_{s,p,t-1}) e^{\zeta_{s,p,t}}",
#   "B.3",       "$\zeta_{s,p,t} \sim N(0, \sigma_{s,p})$",
#   "O.1",       "$I_{s,p,f,t} = q_{s,p,f} \cdot B_{s,p,t}$",
#   "O.2",       "$\hat{q}_{s,p,f} = \frac{\sum_{t|I_{s,p,f,t} \neq 0} (I_{s,p,f,t} - B_{s,p,f,t} ) }{|\{t~|~I_{s,p,f,t} \neq 0\}|},~~ f = 1,2$",
#   "U.1",       "$U_{MSY,s}   = \bar{U}_{MSY} \cdot e^ \epsilon_{U,s}$",
#   "U.2",       "$U_{MSY,s,p} = \bar{U}_{MSY,s} \cdot e^ \epsilon_{(U,s),p}$",
#   "U.3",       "$\epsilon_{U,s} \sim N(0,\sigma_{U})$",
#   "U.4",       "$\epsilon_{(U,s),p} \sim N(0,\sigma_{U})$",
#   "q.1",       "$q_{s,p,f} = q_{s,f} \cdot e^\delta_{q,s,p,f}$",
#   "q.2",       "$delta_{q,s,p,f} \sim N(0,\tau_{q})$",
# )

```

# Appendix C: Omniscient Manager Optimisation

We defined penalty functions so that inside
the desired region the penalty was zero, but outside
the desired region the penalty grew as a cubic function. 
So, for example, a penalty designed to keep a measurement 
$x$ above a the desired region boundary $\epsilon$ is of 
the form
\begin{equation}
\mathcal{P}(x , \epsilon) = \left\{
  \begin{array}{ll}
    0 & x \geq \epsilon, \\
    |x - \epsilon|^2 & x < epsilon. \\
  \end{array} \right. 
\end{equation}
This form has a several advantages over
simple linear penalties, or a logarithmic barrier
penalty [@srinivasan2008tracking]. First, the cubic 
function makes the boundary threshold $\epsilon$ a soft 
boundary, which is able to be crossed if doing favours 
another portion of the objective function, and because
cubics stick closer to the $x$-axis when $|x-\epsilon| < 1$
this boundary is softer than lower degree polynomials. Second, 
making the penalty zero in the desirable region stops
the objective function from favouring regions far
from the boundaries of penalty functions, as a logarithmic
function would, for example, favouring overly conservative
effort series to keep biomass far from the lower depletion
boundary. Third, the cubic form of the penalty outside
the desired region means that the penalty function and its
first two derivatives are continuous with $x$ (**CHECK**),
allowing quasi-newton optimisation methods to be applied. Last,
the cubic polynomial actually favours small excursions
outside of the desired region when it is a net increase
in the objective function, as cubics stick closer to the
$x$-axis than lower degree polynomials.

Each penalty function is applied with a weighting, which
we used as tuning parameters. Tuning was required to balance
the relative contribution of each penalty, depending
on whether it was applied to a time series or point value,
and also to achieve realistic time series of effort or catch.
For example, commercial harvesters are unable to double or triple
effort in a short period of time, as this would require significant
capital investment or a large increase in human resources. 
Similarly, in practice harvesters are reluctant to allow catch 
to increase by more than 10% - 20% per year (**REACH OUT TO
TRAWL FOR INPUT/POSSIBLE CITATION HERE**). Similarly,
there are job-security implications for large sudden drops in
fishing effort. **Tuning criteria?**

We used a cubic spline of effort in each area to reduce
the number of free parameters in the optimisation. For each
area, 9 knot points were distributed across the full 40 year
projection, making them spaced by 5 years. We padded
the omniscient manager simulations by an extra eight
years over the stochastic simulations to avoid any
possible end effects of the spline entering the 
performance metric calculations. Effort splines
were constrained to be between 0 and 120 times the
operating model $E_{MSY,p}$, by replacing any value 
outside that range with the closest
value inside the range (i.e. negative values by *zero*,
large values by $120 E_{MSY_p}$).

From SPC revisions:

We defined penalty functions so that iInside their respective  desired acceptable regions, these penaltiesy was are zeroo, and otherwise but outside the desired region the penalty groew as a cubic function of distance from the desired region. So, fFor example, a penalty designed to keep a performance measurement x above a the desired region boundary ϵ is of the form
P(x | ϵ)={■(0&x≥ϵ,@|x-ϵ|^2&x<epsilon.) ┤
This form has a several advantages over simple linear penalties, or a logarithmic barrier penalty (Srinivasan et al. 2008). First, the cubic  function makes softens the boundary threshold ϵ a soft boundary, effectively  which is able to allowing a cross-over be crossed if doing so favours another portion of the objective function. Second, , and because unlike lower degree polynomials, cubic functionss stick remain closer to the x-axis when |x-ϵ|<1.  this boundary is softer than lower degree polynomials. SecondThird, making the penalty zero penalty within the desirable region stops the objective function from favouring regions far from the boundaries of penalty functions, In contrast, a logarithmic penalty function , as a logarithmic function wouldwould , for example, favouring overly conservative effort series to keep biomass far from the lower depletion boundary. ThirdFinally, outside the desired region, the cubic form of the penalty outside the desired region means that the penalty function and its first two derivatives are continuous with x (CHECK), allowing for fast derivative-based quasi-newton optimisation methodss to be applied. Last, the cubic polynomial actually favours small excursions outside of the desired region when it is a net increase in the objective function, as cubics stick closer to the x-axis than lower degree polynomials .
Each penalty function is applied with a weighting, which we used as tuning parameters. Tuning  via penalty function weights was required to balance the relative contribution of each penalty, depending on whether it was applied to a time series or point value, and also to achieve realistic time series of effort or catch. For example, commercial harvesters are unable to double or triple effort in a short period of time, as this would require significant capital investment or a large increase in human resources. Similarly, in practice harvesters are reluctant to allow catch to increase by more than 10% - 20% per year (REACH OUT TO TRAWL FOR INPUT/POSSIBLE CITATION HERE). Similarly, there are job-security implications for large sudden drops in fishing effort. Tuning criteria?

