# Context

A management strategy evaluation (MSE) process is ongoing for the BC Pacific 
herring fisheries since 2017. A first cycle has been completed 
for all major stocks, with the southern management areas (SOG and
WCVI) completed in 2018 [@benson2020a; @dfo2019a], and the northern 
stocks in 2019 [@dfo2020b]. During the first cycle, technical working groups 
from the major areas identified potential stock structure and the role of 
spawn-on-kelp (SOK) fisheries as important sources of uncertainty that 
should be included in future herring operating models.

Stock structure and spawn-on-kelp fisheries were not represented in existing
stock assessments or operating models for Pacific herring. Therefore, we 
developed a new Spatially Integrated Statistical Catch-at-Age Herring 
(SISCAH) model with the capability of incorporating both of these issues in 
Pacific herring assessments and MSE in an efficient and scientifically 
defensible way.

The Haida Gwaii major Pacific herring area has been closed to fishing 
since 2005. According to the the current non-spatial reference operating 
model, Haida Gwaii herring has been in a sustained high-mortality/low-biomass 
state since the late 1990s, which has inhibited stock growth even in the 
absence of commercial fishing [@dfo2020c]. A Rebuilding Plan is 
being developed for Haida Gwaii herring through a partnership between the 
Council of Haida Nation, DFO, and Parks Canada [@dfo2020b].

In the first MSE cycle, no candidate management procedure, including the
status quo (No Fishing), met the limit reference point performance criterion 
for Haida Gwaii herring [@dfo2020b]. Haida Gwaii operating 
models and management procedures both only recognise large-scale scales and,
therefore, do not contemplate potential spatial diversity in herring 
productivity that may be masked at larger scales. Here, we use the SISCAH
operating model to drive closed loop simulations for Haida Gwaii herring 
and better understand how spatial rebuilding procedures, spawn-on-kelp 
fisheries, and natural mortality patterns potentially affect rebuilding 
dynamics for this area.



## Mandatory paragraph

*The meeting date and title must be exactly as they appear on the Fisheries and Oceans Science Advisory Schedule.
Be sure to use the default text in the French template for the translation as well as the meeting information on the French version of the schedule.
Edit the following sentence as necessary.*

This Science Response Report results from the Science Response 
Process Month Day, Year on the Title of Process Here.

*Add the following sentence if there are other associated publications that will be posted on the schedule.*

Additional publications from this meeting will be posted on the 
\href{http://www.isdm-gdsi.gc.ca/csas-sccs/applications/events-evenements/index-eng.asp}{DFO Science Advisory Schedule} 
as they become available.

