---
title: "Evaluation of potential rebuilding strategies for Pacific Herring (*Clupea pallasii*) in Haida Gwaii"
title_short: "Haida Gwaii Herring Rebuilding Strategies"
title_other: "Insérez le titre ici; il doit correspondre exactement à celui de la page couverture, mais en lettres minuscules (*Nom latin*)"
year: 20XX
month: December
report_number: 999
approver: |
  Approver Name\
  Regional Director
approval_year: 20XX
approval_month: January
approval_day: 01
branch: Science Branch
region: Pacific Region
output:
 csasdown::sr_pdf:
   french: false
   prepub: false
   copy_sty: true
type:
  sr
# ------------
# End of options to set
knit: bookdown::render_book
site: bookdown::bookdown_site
link-citations: true
bibliography: bib/refs.bib
csl: csl/csas.csl
lot: true
lof: true
# Any extra LaTeX code for the header:
header-includes:
- \newcommand{\blandscape}{\begin{landscape}}
- \newcommand{\elandscape}{\end{landscape}}
---

```{r setup, echo=FALSE, cache=FALSE, message=FALSE, results='hide', warning=FALSE}
library(knitr)
library(kableExtra)
if (is_latex_output()) {
  knitr_figs_dir <- "knitr-figs-pdf/"
  knitr_cache_dir <- "knitr-cache-pdf/"
  fig_out_type <- "png"
  kable_format <- "latex"
} else {
  knitr_figs_dir <- "knitr-figs-docx/"
  knitr_cache_dir <- "knitr-cache-docx/"
  fig_out_type <- "png"
  kable_format <- "pandoc"
}
fig_asp <- 0.618
fig_width <- 9
fig_out_width <- "6in"
fig_dpi <- 180
fig_align <- "center"
fig_pos <- "htb"
opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = "#>",
  fig.path = knitr_figs_dir,
  cache.path = knitr_cache_dir,
  fig.asp = fig_asp,
  fig.width = fig_width,
  out.width = fig_out_width,
  echo = FALSE,
  #  autodep = TRUE,
  #  cache = TRUE,
  cache.comments = FALSE,
  dev = fig_out_type,
  dpi = fig_dpi,
  fig.align = fig_align,
  fig.pos = fig_pos
)
options(xtable.comment = FALSE)
options(kableExtra.latex.load_packages = FALSE)
options(knitr.kable.NA = '-')
```

```{r load-libraries, cache=FALSE}
# `french` and `prepub` variables are extracted from the YAML headers above and
#  are used throughout the document. To make the document all in french, change
#  the line in the YAML header above to `french: true`
meta <- rmarkdown::metadata$output
if(length(grep("pdf", names(meta)))){
  french <- meta$`csasdown::sr_pdf`$french
  prepub <- meta$`csasdown::sr_pdf`$prepub
}else if(length(grep("word", names(meta)))){
  french <- meta$`csasdown::sr_word`$french
  prepub <- meta$`csasdown::sr_word`$prepub
}
if(french){
  options(OutDec =  ",")
}

# add other packages here:
library(here)
library(dplyr)
library(readr)
library(tibble)
library(csasdown)

```
